"""English phase-2 content, file B (weekend-dinners, budget-food, eu-food-waste-stats).
Schema: _schema_extra.py. British spelling throughout."""

LANG = "en"

GUIDES2 = {
    "weekend-dinners": dict(
        slug="/en/weekend-dinner-ideas/",
        label="Weekend dinners",
        title="Weekend Dinner Ideas: Friday to Sunday | Cibello",
        desc="Weekend dinner ideas for Friday, Saturday and Sunday: something easy to start with, one dish worth the effort and a Sunday pot that feeds Monday too.",
        eyebrow="Weekend dinner ideas",
        h1="Weekend dinner ideas: Friday night, Saturday supper and the Sunday pot",
        lead="The weekend runs on different rules from the working week. There is more time, more often guests, and usually a bit more appetite for cooking something properly. Here are ideas for Friday, Saturday and Sunday, and a way of letting the weekend's cooking give the week ahead a head start.",
        sections=[
            ("Friday night without the fuss", """<p>Friday is the evening the week finally lets go, and hardly anyone wants to stand at the hob for an hour. Pick something everyone builds for themselves, or something that is on the table in twenty minutes. The plates are allowed to look a little untidy.</p><ul><li><strong>Tacos or fajitas</strong>: everyone fills their own, which suits children and guests alike.</li><li><strong>Homemade pizza</strong>: make the dough in the morning or use a ready-made base, and top it with whatever is left in the fridge.</li><li><strong>Burgers with oven-baked potato wedges</strong>, with or without meat.</li><li><strong>Prawn linguine with lemon and garlic</strong>: twenty minutes from pan to plate, yet it feels like an occasion.</li><li><strong>Bowl night</strong>: rice, salmon or tofu, avocado, pickled red onion and whatever else is around.</li><li><strong>Pulled pork or pulled jackfruit in soft rolls</strong> with a sharp coleslaw.</li><li><strong>Fish finger sandwiches done properly</strong>: good bread, crisp lettuce, a spoon of tartare sauce.</li></ul>"""),
            ("Saturday: simple but a bit special", """<p>A special dinner does not have to be a complicated one. Choose one ingredient to be the centre of the plate and keep everything around it plain: good bread, a green salad, a sauce you have made before.</p><ul><li><strong>Oven-baked salmon with dill, lemon and roast potatoes</strong>.</li><li><strong>Roast chicken thighs with root vegetables and thyme</strong>, all on one tray.</li><li><strong>Fish soup with saffron and aioli</strong>, with crusty bread for dipping.</li><li><strong>Mushroom or asparagus risotto</strong>, depending on the season.</li><li><strong>Steak with béarnaise and potato wedges</strong>.</li><li><strong>Vegetarian lasagne with spinach and ricotta</strong>.</li><li><strong>A grazing board or tapas</strong> made from what is already in: cheese, olives, roasted vegetables, a dip, some cured meat if you have it.</li></ul>"""),
            ("When people are coming round", """<p>Cook something for guests that you have made at least once before and that can be largely prepared in advance. That way you spend the evening at the table rather than at the cooker. Ask about allergies and preferences beforehand and check the ingredients yourself; the allergen filters in Cibello are guidance, not a guarantee. The time you save goes into a pudding or a proper side dish. A stew made the day before and simply reheated is, incidentally, a perfectly good dinner for guests, especially with a fresh salad and bread alongside.</p>"""),
            ("Sunday: today's pot is Monday's lunch", """<p>Sunday is the day for dishes that are happy to sit on a low heat for hours. Conveniently, those are the dishes that are easiest to double.</p><ul><li><strong>Goulash</strong> or <strong>beef bourguignon</strong>.</li><li><strong>Chicken curry</strong> in a big pot.</li><li><strong>Chilli con or sin carne</strong>.</li><li><strong>Lasagne or a pasta bake</strong> in two dishes instead of one.</li><li><strong>A big batch of mince sauce</strong>: half becomes bolognese tonight, half goes into Friday's tacos.</li><li><strong>Sunday roast with the lot</strong>, where the leftover meat and vegetables become a Monday hash or soup.</li></ul><p>Cook double, cool the extra quickly and put it in boxes in the fridge or freezer. In Cibello those boxes can sit in your food inventory alongside everything else, so they are not forgotten at the back of the fridge and simply count as a meal on Monday or Tuesday.</p>"""),
            ("Plan the weekend during the week", """<p>Weekend food often calls for one extra thing: a piece of fish, a particular cheese, a good loaf. If the weekend is already in your <a href="/en/meal-planner/">meal plan</a> by Wednesday, whatever is missing lands on the shared shopping list and whatever you already have gets used first. Cibello also flags what should be eaten before the weekend, so the cream with a short date becomes Sunday's sauce instead of waste. That is one of the quieter ways the weekend helps you <a href="/en/reduce-food-waste/">reduce food waste</a>.</p><p>Would you rather start from what is in the fridge right now? Have a look at <a href="/en/recipes-with-ingredients/">recipes with ingredients you already have</a>. The app ranks more than 9,000 recipes by the share of ingredients you have at home, so a Saturday dinner that needs almost nothing bought comes out near the top. If you are stuck on Friday afternoon, <a href="/en/what-to-eat-tonight/">what to eat tonight</a> has a quick picker to get you unstuck.</p>"""),
            ("A weekend rhythm that runs itself", """<p>Many households find that a loose pattern takes the strain out of weekends: Friday something easy that everyone assembles, Saturday one dish cooked with care, Sunday a pot that also covers Monday. The pattern does not need to be strict. What it mainly does is remove the Friday afternoon question of what is for dinner, and make the Saturday shop fit what is already in the house. Run it for a few weekends and Monday tends to get calmer as well.</p>"""),
        ],
        faq=[
            ("What should we eat on a Friday night?", "Tacos, homemade pizza, burgers, prawn linguine, bowls or pulled pork all work for children and guests and are on the table in thirty to forty minutes."),
            ("What is a simple but special dinner?", "Let one ingredient take centre stage: oven-baked salmon, roast chicken thighs with root vegetables, risotto, fish soup or steak with béarnaise. Keep the sides plain."),
            ("How can weekend cooking help the week ahead?", "Double a Sunday stew or curry, freeze the extra in boxes and put the weekend in your meal plan during the week so the shopping goes on one list."),
            ("How does Cibello help with the weekend?", "The app shows what is in the house and what needs eating soon, suggests recipes that fit, and puts only what is missing on the shared shopping list."),
        ],
    ),

    "budget-food": dict(
        slug="/en/budget-meals/",
        label="Budget meals",
        title="Budget Meals for a Whole Week | Cibello",
        desc="Budget meals start with knowing what you have: a weekly menu built from the store cupboard, buying only what is missing and using everything up.",
        eyebrow="Budget meals",
        h1="Budget meals for a whole week: plan, buy less and use what you have",
        lead="The cheapest food is the food you have already bought. Most households throw away a surprising amount each year, mostly through buying things twice and forgetting what is in the fridge. This is a practical route to eating well for less, built on knowing what you have rather than eating the same thing every night.",
        sections=[
            ("Why does food end up costing so much?", """<p>Ask people where the grocery money goes and the same five answers come back.</p><ul><li><strong>Impulse buys</strong> when dinner has not been decided.</li><li><strong>Buying twice</strong>: a second jar of something already at the back of the cupboard.</li><li><strong>Waste</strong>: vegetables, dairy and leftovers that go off before their turn.</li><li><strong>Expensive protein every day</strong> instead of a mix of meat, fish, eggs and pulses.</li><li><strong>Takeaway</strong> on evenings when energy is gone and nothing was planned.</li></ul><p>Every one of these has the same remedy: know what you have, decide in advance and shop from a list.</p>"""),
            ("A budget weekly menu that starts in the cupboard", """<p>The store cupboard is the foundation of cheap cooking: pasta, rice, bulgur wheat, lentils, tinned beans, chopped tomatoes, oats, eggs and a bag or two of frozen vegetables. With those in place you need to buy relatively little fresh. A budget <a href="/en/meal-planner/">weekly menu</a> might look like this.</p><div class="table-wrap"><table class="cmp"><caption>An example week built around the store cupboard, with leftovers planned in from the start.</caption><thead><tr><th scope="col">Day</th><th scope="col">Dish</th><th scope="col">What keeps the cost down</th></tr></thead><tbody><tr><th scope="row">Mon</th><td>Lentil soup with bread</td><td>Dried lentils, carrots, cupboard spices</td></tr><tr><th scope="row">Tue</th><td>Pasta with tomato sauce and beans</td><td>Chopped tomatoes, tinned beans</td></tr><tr><th scope="row">Wed</th><td>Omelette with leftover vegetables</td><td>Eggs, whatever needs using</td></tr><tr><th scope="row">Thu</th><td>Chicken curry with rice (double batch)</td><td>Chicken thighs, coconut milk, frozen vegetables</td></tr><tr><th scope="row">Fri</th><td>Tacos with mince or beans</td><td>Half mince, half beans</td></tr><tr><th scope="row">Sat</th><td>Leftovers: curry in a box or as wraps</td><td>Nothing new bought</td></tr><tr><th scope="row">Sun</th><td>Tray bake with sausages, potatoes and root vegetables</td><td>Seasonal roots</td></tr></tbody></table></div><p>Notice what the week does. Two of the seven dinners cost nothing extra because they were planned as leftovers. Meat appears twice, stretched with beans both times. Nothing needs to be bought in a hurry on the way home.</p>"""),
            ("Buy only what is missing", """<p>The single biggest saving is to stop buying what you already own. Once your food inventory is in Cibello, each planned dish is compared with what is at home and only the difference goes onto the shared shopping list. Photograph the receipt after the shop and the inventory is updated again. It is a simple loop: plan, shop the list, cook, repeat. If you want to see what the fridge can already make before you plan anything, <a href="/en/recipes-with-ingredients/">recipes with ingredients you have</a> ranks more than 9,000 recipes by the share of ingredients already in the house, and shows which ones are missing. The <a href="/en/pantry-app/">pantry app guide</a> explains how the inventory is built from photos of the fridge, freezer and cupboard, and why you check what the AI recognised before it is saved.</p>"""),
            ("Cheap protein and the seasonal shelf", """<p>Protein is usually the most expensive part of a plate, so it is where the menu has most room to move. Eggs, lentils, chickpeas, tinned beans and tofu are cheap and keep for months. Chicken thighs and drumsticks cost less than breast and taste better slow-cooked. Tinned fish works in pasta, fishcakes and salads. A cheap week does not mean a meat-free week; it means meat is one of several options rather than the default every night. Vegetables follow the same logic. Whatever is in season and piled high at the front of the shop is generally the best value, and frozen peas, spinach and mixed vegetables cost little and never go off before you get to them.</p>"""),
            ("Use everything: leftovers, short dates and the freezer", """<p>Dishes that use ingredients with a short date belong early in the week, and leftovers should be planned in as boxed lunches or the next night's dinner rather than left to chance. Cibello draws your attention to items approaching their best-before date and suggests recipes where they are put to use. In that way <a href="/en/reduce-food-waste/">less food waste</a> becomes a result of the planning, not a separate effort you have to keep up. The freezer is your ally here: half a loaf, a portion of stew, the last of the mince. Label the box and put the box in the inventory, and it stops being a mystery parcel and becomes a Thursday dinner.</p>"""),
            ("Cheap and healthy at the same time", """<p>A budget menu is often also a reasonably healthy one, because the cheap staples, pulses, eggs, whole grains, frozen and seasonal vegetables, are the foods most dietary advice leans on anyway. The nutrition values shown in the app are estimates, not dietary advice, and the allergen and recipe filters are guidance rather than a guarantee. What the approach does deliver, week after week, is fewer impulse buys, less thrown away and a shopping trolley that matches the plan. For most households that is where the money was going all along.</p>"""),
        ],
        faq=[
            ("How do you eat cheaply for a whole week?", "Start from the store cupboard, plan five to seven dinners with leftovers built in, put dishes with short-dated ingredients early in the week and buy only what is missing."),
            ("Which foods are cheapest to build dinners around?", "Pasta, rice, bulgur wheat, lentils, tinned beans, eggs, chopped tomatoes, oats, seasonal root vegetables and frozen vegetables."),
            ("How does Cibello help me save money on food?", "The app keeps track of what you have, suggests recipes that use it and puts only what is missing on the shopping list, which cuts down on buying twice and on waste."),
            ("Is a budget weekly menu also healthy?", "It can be. Pulses, vegetables, eggs and whole grains are both cheap and nutritious. Nutrition values in the app are estimates, not dietary advice."),
        ],
    ),

    "eu-food-waste-stats": dict(
        slug="/en/food-waste-statistics-eu/",
        label="Food waste statistics",
        title="Food Waste Statistics for the EU | Cibello",
        desc="How much food is wasted in the EU? Eurostat figures on food waste per person and by sector, the 2030 EU target and where to find country data.",
        eyebrow="Food waste in figures",
        h1="Food waste statistics for the EU: how much do we actually throw away?",
        lead="This page collects the official Eurostat figures on food waste in the European Union: total tonnes, kilograms per inhabitant and which part of the chain wastes most, with a link to the source. It is updated when Eurostat publishes new estimates.",
        sections=[
            ("EU food waste at a glance (2023)", """<div class="table-wrap"><table class="cmp"><caption>Food waste as measured by Eurostat includes edible and inedible parts (peel, bones, coffee grounds) and is reported as fresh mass. Reference year 2023.</caption><thead><tr><th scope="col">Measure</th><th scope="col">Value</th><th scope="col">Source</th></tr></thead><tbody><tr><th scope="row">Total food waste in the EU</th><td>58.2 million tonnes</td><td>Eurostat, estimates for 2023</td></tr><tr><th scope="row">Compared with 2022</th><td>57.8 million tonnes, an increase of 0.7 %</td><td>Eurostat</td></tr><tr><th scope="row">Per inhabitant</th><td>about 130 kg per year</td><td>Eurostat</td></tr><tr><th scope="row">Households' share</th><td>53 %, about 31 million tonnes</td><td>Eurostat</td></tr><tr><th scope="row">Households per inhabitant</th><td>69 kg per year</td><td>Eurostat</td></tr></tbody></table></div><p>Source: <a href="https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Food_waste_and_food_waste_prevention_-_estimates" rel="noopener">Eurostat, Food waste and food waste prevention: estimates</a>, together with the Eurostat news release of 16 October 2025 on 130 kg of food wasted per person annually in the EU.</p>"""),
            ("Who wastes the most?", """<div class="table-wrap"><table class="cmp"><caption>Distribution of EU food waste across the supply chain, 2023. Source: Eurostat.</caption><thead><tr><th scope="col">Stage</th><th scope="col">Share</th><th scope="col">Kg per inhabitant per year</th></tr></thead><tbody><tr><th scope="row">Households</th><td>53 %</td><td>69</td></tr><tr><th scope="row">Manufacture of food products and beverages</th><td>19 %</td><td>24</td></tr><tr><th scope="row">Restaurants and food services</th><td>11 %</td><td>14</td></tr><tr><th scope="row">Primary production (farming, fishing)</th><td>10 %</td><td>12</td></tr><tr><th scope="row">Retail and other distribution</th><td>8 %</td><td>10</td></tr></tbody></table></div><p>More than half of all food waste in the EU happens at home. That is an uncomfortable figure, but also an encouraging one: the largest part of the problem sits in habits that individual households can change, without waiting for industry or legislation. Part of those 69 kilograms is unavoidable, such as peel and bones. The rest is food bought with good intentions and then forgotten.</p><p>The order is not accidental either. At the start of the chain, businesses work with large volumes and tight planning; at home, people shop for a week that rarely goes exactly as expected. That is why the household is also the place where a small change in habits makes the biggest difference.</p>"""),
            ("The EU target for 2030", """<p>With the 2025 revision of the Waste Framework Directive, the EU set binding food waste reduction targets for the first time. By 2030, food waste in processing and manufacturing is to fall by 10 %, and food waste in retail, restaurants, food services and households together is to fall by 30 % per capita. Both targets are measured against the average for 2021 to 2023. These are EU-wide targets; how each member state gets there is a national matter, and this page does not attempt to summarise national plans.</p>"""),
            ("Figures by country", """<p>Alongside the EU total, Eurostat publishes figures for each member state, and national statistics offices publish their own country data, often with more detail on what households actually throw away. The two are not always directly comparable, because measurement methods and definitions vary from country to country. If you want to compare your own country with the EU average, the Eurostat tables are the safest place to do it, since one definition applies to everyone. This page deliberately stays at EU level. When you read national figures, check the reference year and whether inedible parts are included. For Sweden, this site has a separate page with national figures, <a href="/matsvinn-statistik/">matsvinn i Sverige</a>, written in Swedish and based on the Swedish Environmental Protection Agency and the Swedish Food Agency.</p>"""),
            ("What the figures mean for a household", """<p>Sixty-nine kilograms per person per year is a bag of shopping every week or so, much of it fruit, vegetables, bread and leftovers that were meant to be eaten. Surveys across Europe keep pointing to the same remedies: plan a few dinners at a time, shop from a list, store food properly and use what has the shortest date first. None of it is complicated; the difficulty is keeping it up when the week gets busy. Read <a href="/en/reduce-food-waste/">how to reduce food waste at home</a>, and see how a <a href="/en/meal-planner/">meal planner</a> that knows what is already in the fridge turns it from a project into a habit. Cibello builds a food inventory from photos of your fridge, freezer and cupboard, shows what needs eating soon and suggests recipes from what is there. You check what the AI recognised before it is saved, since it can misread a label.</p>"""),
            ("If you want to cite this page", """<p>You are welcome to use the figures with a reference to Eurostat as the original source. If you want to cite this summary: "Cibello, Food waste statistics for the EU, cibello.app/en/food-waste-statistics-eu/, updated September 2026". Questions about the page: <a href="mailto:hello@cibello.app">hello@cibello.app</a>.</p>"""),
        ],
        faq=[
            ("How much food is wasted in the EU each year?", "About 58.2 million tonnes in 2023 according to Eurostat, or roughly 130 kg per inhabitant. Households account for 53 percent of the total."),
            ("How much food does a household throw away?", "Eurostat puts household food waste at 69 kg per inhabitant per year, including inedible parts such as peel and bones."),
            ("What is the EU target for food waste?", "By 2030, a 10 percent reduction in processing and manufacturing and a 30 percent reduction per capita in retail, restaurants, food services and households, compared with the 2021 to 2023 average."),
            ("Where can I find food waste figures for my country?", "Eurostat publishes figures per member state, and national statistics offices publish their own country data. Check the reference year and definitions before comparing."),
        ],
    ),
}
