"""Finnish content, phase 2, file A. See _schema_extra.py for the structure.

Rules: docs/OVERSATTNINGSBRIEF.md and tools/content/_phase2_brief.md. Facts: docs/FAKTAKONTROLL.md only.
Families here: everyday-food, quick-dinner, family-dinner, meal-boxes, shopping-list, best-before,
weekday-dinners, what-to-eat-tonight, plus TOOL (the dinner picker).
"""

LANG = "fi"

GUIDES2 = {
    "everyday-food": dict(
        slug="/fi/arkiruoka/",
        label="Arkiruoka",
        title="Arkiruoka: helppoja ruokia koko viikoksi | Cibello",
        desc="Arkiruoka, joka valmistuu siinä ajassa, joka illalla on, ja niistä aineksista, jotka jo ovat kotona. Näin suunnittelet viikon ruoat ilman iltapäivän stressiä.",
        eyebrow="Arkiruokaa ilman stressiä",
        h1="Arkiruoka: helppoja ruokia, jotka toimivat koko viikon",
        lead="Hyvä arkiruoka ei vaadi uusia reseptejä joka päivä. Se vaatii, että tiedät, mitä kotona on, ja että ruoka valmistuu siinä ajassa, joka illalla oikeasti on käytettävissä. Cibello aloittaa jääkaapista, sinä päätät loput.",
        sections=[
            ("Millaista on hyvä arkiruoka?", """<p>Hyvällä arkiruoalla on kolme ominaisuutta: se valmistuu siinä ajassa, joka illalla on, se perustuu aineksiin, joita sinulla jo on tai jotka saat helposti, ja sitä voi vaihdella niin, ettei kukaan kyllästy. Kyse on harvoin uusista resepteistä. Useimmat taloudet kierrättävät 10–15 ruokaa, ja se on täysin järkevää. Ero stressaavan ja rauhallisen ruoka-arjen välillä syntyy yleensä suunnittelusta ja yleiskuvasta, ei kokkaustaidoista.</p><p>Arki on myös ennakoitavaa. Maanantaina on kiire, keskiviikkona joku tulee myöhään harrastuksista ja perjantaina jaksaminen on vähissä. Kun ruoat suunnitellaan näiden realiteettien mukaan eikä ihanneviikon mukaan, ne myös toteutuvat. Makaronilaatikko, lohikeitto, jauhelihakastike ja uunipelti nakeista ja juureksista eivät ole tylsiä valintoja vaan ruokia, jotka kantavat viikosta toiseen, kunhan niitä vaihdellaan.</p>"""),
            ("Arkiruokareseptejä, jotka alkavat jääkaapista", """<p>Useimmat reseptisivustot aloittavat väärästä päästä: valitset ruoan ja huomaat sitten, että puolet aineksista puuttuu. Cibello kääntää järjestyksen. Kun jääkaappi, pakastin ja kuivakaappi on kirjattu sovellukseen, kuvaamalla ne tai skannaamalla kuitit, sovellus vertaa ruokavarastoasi yli 9 000 reseptiin ja näyttää, kuinka suuri osa aineksista sinulla jo on. Ruoat, joiden aineksista 80–100 prosenttia löytyy kotoa, nousevat ylimmäksi. Näin <a href="/fi/reseptit-aineksista/">reseptit kotona olevista aineksista</a> ovat oikeasti tehtävissä samana iltana, eivät vain inspiroivia.</p><ul><li><strong>Pasta ja nuudelit</strong>: kaapissa on lähes aina jotakin, ja loput löytyy jääkaapista.</li><li><strong>Munakas, frittata ja letut</strong>: pelastavat kananmunat, maidon ja pian vanhenevat kasvikset.</li><li><strong>Keitot ja padat</strong>: sietävät tähteitä ja muuttuvat seuraavan päivän <a href="/fi/lounasevaat/">lounaseväiksi</a>.</li><li><strong>Wokit ja kulhoruoat</strong>: käyttävät puolikkaat kasvikset sekä keitetyn riisin tai ohran.</li><li><strong>Uuniruoat</strong>: juurekset, kana tai kala pellillä, omaa työtä vain muutama minuutti.</li></ul>"""),
            ("Arkiruokaa koko viikoksi", """<p>Kun suunnittelet viisi arkipäivää kerralla, jokainen yksittäinen ilta helpottuu. Hyvä <a href="/fi/ateriasuunnittelu/">viikkosuunnitelma</a> ottaa huomioon, milloin on aikaa, mikä pitäisi käyttää ensin ja mistä ruoista jää tähteitä seuraavalle päivälle. Cibello vaihtelee raaka-aineita ja ateriatyyppejä niin, ettei sama ruoka toistu useana päivänä peräkkäin, ja kokoaa puuttuvat ainekset <a href="/fi/ostoslista/">jaettuun ostoslistaan</a>. Tarkistat ja muokkaat suunnitelman ennen viikon alkua: ehdotukset ovat apu, eivät vaatimus.</p><p>Moni huomaa, että kolme tai neljä suunniteltua päivällistä riittää. Loput illat hoituvat tähteillä, eväillä tai sillä, mitä sattuu tekemään mieli. Suunnitelma, jossa on tilaa, kestää arkea paremmin kuin täydellinen seitsemän päivän lista, joka kaatuu ensimmäiseen yllätykseen.</p>"""),
            ("Nopeaa, edullista ja lapsille sopivaa arkiruokaa", """<p>Arkiruokaa joutuu viikosta riippuen viilaamaan eri suuntiin. Jos aikaa on vähän, <a href="/fi/nopea-ruoka/">nopea ruoka 20–30 minuutissa</a> on oikea lähtökohta. Jos lapset suosivat tuttua, <a href="/fi/lapsiperheen-ruoka/">lapsiperheen ruokaideat</a> auttavat vaihtelemaan tutun sisällä. Ja jos ruokabudjetti on tiukka, kannattaa aloittaa siitä, mitä kaapissa jo on, ja ostaa vain se, mikä puuttuu. Cibello lähtee liikkeelle kotona olevista aineksista, talouden allergioista ja ruokatottumuksista, ja sovellus oppii ajan myötä, mitä teillä yleensä valitaan. Jokainen ehdotus tulee selityksen kanssa, esimerkiksi siksi, että kerma vanhenee pian tai että ruoka muistuttaa jotakin, mistä olette pitäneet.</p>"""),
            ("Näin arkiruoka pysyy hallinnassa pitkään", """<ol><li>Kirjaa kotona olevat ruoat kerran ja päivitä varasto kauppareissun yhteydessä, esimerkiksi kuvaamalla kuitti. Tarkista tunnistetut tuotteet ennen tallennusta, sillä tekoäly voi tulkita väärin.</li><li>Anna ehdotusten lähteä ruokavarastosta tyhjän sijaan.</li><li>Suunnittele 3–5 päivällistä kerralla, ei seitsemää. Jätä tilaa tähteille ja spontaaniudelle.</li><li>Tee tuplasatsi ruoista, jotka sen kestävät, ja pakasta eväät.</li><li>Tarkista aina itse ainekset, allergeenit ja päiväykset. Sovellus on tuki, ei takuu.</li></ol>"""),
            ("Koko talous samalla sivulla", """<p>Arkiruoan raskain osa on usein se, että yksi ihminen kantaa kaiken päässään: mitä on, mitä puuttuu, mitä syödään. Cibellossa talouden jäsenet näkevät saman ruokavaraston, saman suunnitelman ja saman ostoslistan. Kun joku käyttää viimeiset kananmunat tai ostaa maitoa kotimatkalla, kaikki näkevät sen. Sovellus on tarkoitettu aikuisille, ja yhteinen näkymä on käytössä 14 päivän kokeilujakson aikana ilman korttia sekä sen jälkeen maksullisella tilauksella. Kun jokin ruoka on vanhenemassa, sovellus muistuttaa siitä ystävällisesti, ilman syyllistämistä. Se on helpoin tapa <a href="/fi/vahenna-ruokahavikkia/">vähentää ruokahävikkiä</a> tekemättä mitään ylimääräistä.</p>"""),
        ],
        faq=[
            ("Mitä arkiruoalla tarkoitetaan?", "Arkiruoka on ruokaa, jonka ehtii tehdä tavallisena arki-iltana: nopeaa, kotona olevista tai helposti saatavista aineksista ja vaihdeltavissa viikon mittaan."),
            ("Miten löydän arkiruokareseptejä siitä, mitä kotona on?", "Cibellossa kirjaat jääkaapin, pakastimen ja kaapit kuvaamalla tai skannaamalla. Sovellus vertaa ruokavarastoa resepteihin ja näyttää, kuinka suuri osa aineksista sinulla jo on. Tarkista tunnistetut tuotteet ennen tallennusta, sillä tekoäly voi tulkita väärin."),
            ("Voiko Cibello suunnitella arkiruoat koko viikoksi?", "Kyllä. Cibello voi ehdottaa viikkosuunnitelman, joka vaihtelee ruokia ja raaka-aineita ja lisää puuttuvat ainekset jaettuun ostoslistaan. Tarkistat ja muokkaat suunnitelman itse."),
            ("Ottavatko ehdotukset huomioon allergiat?", "Voit merkitä allergiat ja ruokatottumukset, mutta suodatus on ohjeellinen eikä takuu. Tarkista aina itse ainekset ja pakkaukset."),
        ],
    ),

    "quick-dinner": dict(
        slug="/fi/nopea-ruoka/",
        label="Nopea ruoka",
        title="Nopea ruoka: päivällinen 20–30 minuutissa | Cibello",
        desc="Nopea ruoka kaatuu harvoin reseptiin, useammin siihen, että kaksi ainesta puuttuu. Ruokia, jotka valmistuvat lähes aina, ja tapa saada ehdotus alle minuutissa.",
        eyebrow="Päivällinen 20–30 minuutissa",
        h1="Nopea ruoka: päivällinen 20–30 minuutissa siitä, mitä kotona on",
        lead="Nopea ruoka kaatuu harvoin reseptiin ja useimmiten siihen, että kaksi ainesta puuttuu. Tässä oppaassa on ruokia, jotka valmistuvat lähes aina kotona olevista aineksista, ja tapa saada ehdotus alle minuutissa.",
        sections=[
            ("Miksi nopea ruoka epäonnistuu", """<p>Useimmat nopean ruoan reseptit olettavat, että kaikki on jo kotona. Todellisuudessa pari asiaa puuttuu, ja 20 minuuttia venyy 50:een kauppareissun takia. Toinen yleinen ongelma on, että kaikki nopeat ruoat alkavat muistuttaa toisiaan: pastaa, pastaa ja pastaa. Ratkaisu on antaa ehdotusten lähteä siitä, mitä sinulla oikeasti on, ja antaa jonkun muun pitää huolta vaihtelusta.</p><p>Kolmas syy on päätösväsymys. Kello 17 ei jaksa selata reseptejä, ja siksi valinta osuu samaan kolmeen ruokaan tai noutoruokaan. Kun vaihtoehdot on valmiiksi rajattu sen mukaan, mitä kaapissa on, päätös kestää sekunteja eikä varttia.</p>"""),
            ("Helppoja ruokia, jotka valmistuvat lähes aina", """<div class="table-wrap"><table class="cmp"><caption>Nopeita arkiruokia ja niiden perusainekset</caption><thead><tr><th scope="col">Ruoka</th><th scope="col">Aika</th><th scope="col">Perustuu</th></tr></thead><tbody><tr><th scope="row">Pasta jääkaapin aineksista</th><td>15–20 min</td><td>Pasta, juusto, kasvikset, mahdollisesti pekoni tai kikherneet</td></tr><tr><th scope="row">Munakas tai frittata</th><td>15 min</td><td>Kananmunat, kasvistähteet, juusto</td></tr><tr><th scope="row">Wokki riisillä tai nuudeleilla</th><td>20 min</td><td>Puolikkaat kasvikset, proteiini, soija</td></tr><tr><th scope="row">Tacot ja wrapit</th><td>20 min</td><td>Jauheliha, pavut tai kana, tortillat</td></tr><tr><th scope="row">Pyttipannu</th><td>20 min</td><td>Keitetyt perunat, tähteet, kananmuna</td></tr><tr><th scope="row">Keitto juureksista tai linsseistä</th><td>25–30 min</td><td>Kuivakaappi ja se, mikä pitää käyttää</td></tr><tr><th scope="row">Uunikala ja kasvikset</th><td>25 min</td><td>Pakastekala, perunat, sitruuna</td></tr><tr><th scope="row">Lohikeitto</th><td>30 min</td><td>Lohi tai pakastekala, perunat, kerma, tilli</td></tr><tr><th scope="row">Nopea pata kanasta tai kikherneistä</th><td>25–30 min</td><td>Tomaattimurska, kookosmaito, mausteet</td></tr></tbody></table></div><p>Yhteistä näille ruoille on, että ne sietävät vaihdoksia. Jos kanaa ei ole, pavut käyvät; jos paprika puuttuu, porkkana kelpaa. Cibello näyttää, mitkä ainekset sinulla on ja mitkä puuttuvat, joten näet nopeasti, onnistuuko resepti sellaisenaan vai pitääkö sitä soveltaa.</p>"""),
            ("Näin saat ruokaehdotuksen alle minuutissa", """<ol><li>Kuvaa jääkaappi ja kaapit. Sovellus tunnistaa tuotteet ja rakentaa ruokavarastosi. Tarkista tulos ennen tallennusta, sillä tekoäly voi tulkita väärin.</li><li>Kysy ”mitä syötäisiin” ja selaa ehdotuksia, jotka perustuvat kotona oleviin aineksiin ja siihen, mikä pitää käyttää ensin.</li><li>Valitse ruoka, jonka aineksista mahdollisimman suuri osa on jo kotona.</li><li>Lisää mahdolliset täydennykset ostoslistaan.</li></ol><p>Ehdotukset ottavat huomioon myös sen, mikä on vanhenemassa. Nopea ruoka, joka samalla pelastaa pian vanhenevan kerman, on kaksin verroin hyvä. Lue lisää siitä, miten <a href="/fi/parasta-ennen/">parasta ennen -päiväys</a> kannattaa tulkita ja miten <a href="/fi/vahenna-ruokahavikkia/">ruokahävikkiä vähennetään</a> arjessa.</p>"""),
            ("Nopea ruoka lapsiperheessä", """<p>Lasten kanssa nopean ruoan pitää usein olla myös tuttua. Tacot, letut, lihapullat ja pasta tomaattikastikkeella toimivat syystä. Niksi on vaihdella lisukkeita ja proteiinia, ei itse ruokaa: sama pasta kanalla yhtenä viikkona ja papujen kanssa seuraavana, samat tacot kalalla jauhelihan sijaan. Lisää ideoita löydät oppaasta <a href="/fi/lapsiperheen-ruoka/">lapsiperheen ruokaideat</a>, ja jos haluat suunnitella hieman pidemmälle, <a href="/fi/ateriasuunnittelu/">ateriasuunnittelu</a> auttaa kokoamaan nopeista arkiruoista koko viikon.</p>"""),
            ("Nopea ruoka ilman kauppareissua", """<p>Pienikin perusvarasto kantaa pitkälle. Pasta, riisi, kananmunat, tomaattimurska, pakastekasvikset, sipuli, juusto ja purkillinen papuja riittävät moneen päivälliseen ilman, että kaupassa tarvitsee käydä. Kun nämä on kirjattu Cibellon ruokavarastoon, sovellus näkee ne aina, myös sen purkin, joka on jäänyt kaapin perälle. Ja kun ostat täydennystä, kuvaat kuitin ja varasto on taas ajan tasalla.</p><p>Lisää ruokaideoita ajan mukaan järjestettynä on oppaassa <a href="/fi/ruokaideoita-arkeen/">ruokaideoita arkeen</a>. Jos taas haluat vain nopean vastauksen ilman selaamista, <a href="/fi/mita-tanaan-syotaisiin/">ruokavalitsin</a> arpoo ehdotuksen proteiinin, ajan ja tilanteen mukaan.</p>"""),
        ],
        faq=[
            ("Mikä on nopea ruoka?", "Nopea ruoka valmistuu 20–30 minuutissa aineksista, joita sinulla jo on kotona, ilman että ensin pitää käydä kaupassa."),
            ("Miten löydän nopean ruoan siitä, mitä kotona on?", "Kirjaa jääkaappi ja kaapit Cibelloon kuvaamalla ne. Sovellus vertaa ruokavarastoa resepteihin ja näyttää ruoat, jotka voit tehdä nyt, pian vanhenevat ainekset ensin."),
            ("Näenkö, mitä reseptistä puuttuu?", "Kyllä. Cibello näyttää jokaisesta reseptistä, mitkä ainekset puuttuvat. Tarkista aina itse ainekset ja allergeenit."),
            ("Mitkä nopeat ruoat sopivat lapsille?", "Tacot, letut, pasta tomaattikastikkeella ja lihapullat toimivat usein. Vaihtele lisukkeita ja proteiinia koko ruoan sijaan."),
        ],
    ),

    "family-dinner": dict(
        slug="/fi/lapsiperheen-ruoka/",
        label="Lapsiperheen ruoka",
        title="Lapsiperheen ruoka: ideoita, jotka lapset syövät | Cibello",
        desc="Lapsiperheen arkiruokaa, jonka lapset oikeasti syövät: ruokaperheitä, joita voi vaihdella, viikon ruokalista, allergiat ja tapa jakaa muistikuorma aikuisten kesken.",
        eyebrow="Ruokaa, joka kelpaa lapsille",
        h1="Lapsiperheen ruoka: arkiruokaa, jonka lapset oikeasti syövät",
        lead="Lapset pitävät tutusta, ja se on ihan hyvä. Vaihtelu kannattaa tehdä tutun sisällä: sama pasta eri kastikkeella, samat tacot eri täytteellä. Tässä oppaassa on ideoita, viikkorytmi ja pari ajatusta siitä, miten sovellus voi kantaa osan muistikuormasta.",
        sections=[
            ("Lapsille sopivia ruokia, joita voi vaihdella", """<p>Useimmat lapset pitävät tutusta. Se ei tarkoita, että joka viikko pitäisi syödä samaa, vaan että vaihtelun pitää tapahtua lapsille tuttujen ruokien sisällä. Ajattele ruokaperheitä yksittäisten reseptien sijaan:</p><ul><li><strong>Pasta</strong>: tomaattikastike, jauhelihakastike, kana ja kerma, pesto, juusto ja parsakaali.</li><li><strong>Makaronilaatikko ja muut uunilaatikot</strong>: jauhelihalla, kinkulla tai kasvisversiona, tuplasatsi eväiksi.</li><li><strong>Tacot ja wrapit</strong>: jauheliha, kana, pavut tai kala, ja lapset kokoavat itse.</li><li><strong>Letut ja pannukakku</strong>: pinaattiletut, ohukaiset marjojen kanssa tai täytettyinä.</li><li><strong>Lihapullat ja pihvit</strong>: liha, kana tai kasvis, muusin, perunoiden tai pastan kanssa.</li><li><strong>Uunipelti</strong>: nakit tai kana juuresten kanssa, kaikki samalla pellillä.</li><li><strong>Keitto ja leipä</strong>: lohikeitto, tomaattikeitto, kanakeitto tai kesäkeitto, pienimmille soseutettuna.</li></ul>"""),
            ("Viikon ruokalista perheelle", """<p>Viikon ruokalista vähentää nalkutusta molempiin suuntiin: lapset tietävät, mitä on tulossa, eikä sinun tarvitse improvisoida kello 17. Monelle toimii rytmi, jossa on kaksi nopeaa suosikkia, yksi uusi ruoka, yksi tähdepäivä ja yksi perjantairuoka, jota kaikki odottavat. Cibellossa lisäät ruoat päiväkohtaisesti <a href="/fi/ateriasuunnittelu/">viikkosuunnitelmaan</a>, ja puuttuvat ainekset siirtyvät <a href="/fi/ostoslista/">jaettuun ostoslistaan</a>, jotta se, joka käy kaupassa kotimatkalla, näkee saman listan.</p><p>Uuden ruoan kannattaa muistuttaa jotakin tuttua. Jos tacot kelpaavat, kanawrapit menevät läpi todennäköisemmin kuin curry. Jos makaronilaatikko on suosikki, kasvislasagne on pienempi loikka kuin linssikeitto. Uusi ruoka kannattaa myös sijoittaa päivään, jolloin kukaan ei ole nälkäisimmillään tai väsyneimmillään.</p>"""),
            ("Nopeasti ja edullisesti tinkimättä ravinnosta", """<p>Lapsiperheessä on harvoin aikaa kokata pitkään arkisin, ja ruoka on iso menoerä. Sekä <a href="/fi/nopea-ruoka/">nopean ruoan</a> että edullisen ruoan perusta on sama: käytä se, mitä on, suunnittele tähteet ja osta pääasiassa vain se, mikä puuttuu. Cibello näyttää ravintoarvot suunnittelun tueksi, mutta ne ovat arvioita eivätkä ravitsemusneuvontaa. Jos lapsella on erityistarpeita, kysy neuvolasta tai terveydenhuollosta.</p>"""),
            ("Allergiat ja lapset", """<p>Jos lapsella on allergia tai intoleranssi, sen voi merkitä talouden profiiliin, jolloin ehdotukset suodattuvat sen mukaan. Suodatus on kuitenkin ohjeellinen, ei koskaan takuu. Lue aina ainesosaluettelo ja tarkista pakkaus itse, erityisesti silloin, kun reseptiä muutetaan tai tuote vaihtuu toiseen. Sama koskee tekoälyn tunnistamia tuotteita: tarkista ne ennen tallennusta, sillä kuva voi tulkkiutua väärin.</p>"""),
            ("Anna lasten osallistua", """<p>Lapsi, joka saa valita kahdesta ruoasta tai koota oman tacon, suhtautuu ruokapöytään useammin myönteisesti. Sovellus on tarkoitettu aikuisille (18 vuotta täyttäneille), mutta valinnan voi hyvin tehdä yhdessä keittiön pöydän ääressä. Cibello on rakennettu koko taloudelle: kaikki aikuiset näkevät saman ruokavaraston, suunnitelman ja ostoslistan, ja ehdotukset oppivat, mistä teillä pidetään, ilman että kenenkään tarvitsee pitää kaikkea päässään. Yhteinen näkymä on käytössä 14 päivän kokeilujakson aikana ja sen jälkeen maksullisella tilauksella.</p>"""),
            ("Kun tähteet ovat osa suunnitelmaa", """<p>Perheessä tähteet ovat pikemminkin sääntö kuin poikkeus. Tuplasatsi makaronilaatikkoa tai jauhelihakastiketta on seuraavan päivän lounas tai keskiviikon pelastus. Kun kirjaat tähteet Cibelloon <a href="/fi/lounasevaat/">eväinä</a>, ne näkyvät ruokavarastossa ja sovellus muistuttaa, kun ne pitäisi syödä. Se säästää rahaa ja on helpoin tapa <a href="/fi/vahenna-ruokahavikkia/">vähentää ruokahävikkiä</a> lapsiperheessä, jossa lautaselle jää aina jotakin.</p>"""),
        ],
        faq=[
            ("Mistä ruoista lapset yleensä pitävät?", "Pasta, tacot, letut, lihapullat, makaronilaatikko ja uunipeltiruoat toimivat monelle lapselle. Vaihtele kastikkeita, lisukkeita ja proteiinia koko ruoan sijaan."),
            ("Miten teen viikon ruokalistan perheelle?", "Valitse kaksi nopeaa suosikkia, yksi uusi ruoka, yksi tähdepäivä ja yksi viikonloppuruoka. Cibellossa lisäät ruoat päiväkohtaisesti ja saat puuttuvat ainekset jaettuun ostoslistaan."),
            ("Voiko Cibello ottaa huomioon lasten allergiat?", "Voit merkitä allergiat talouden profiiliin, mutta suodatus on ohjeellinen. Tarkista aina itse ainekset ja pakkaukset."),
            ("Onko sovelluksen ravintoarvot tarkoitettu lapsille?", "Ravintoarvot ovat arvioita suunnittelun tueksi, eivät ravitsemusneuvontaa. Erityistarpeissa kysy neuvolasta tai terveydenhuollosta."),
        ],
    ),

    "meal-boxes": dict(
        slug="/fi/lounasevaat/",
        label="Lounaseväät",
        title="Lounaseväät: suunnittele ja säilytä oikein | Cibello",
        desc="Eväät, jotka kestävät jääkaapissa ja mikrossa: mitkä ruoat sopivat eväiksi, miten suunnittelet viikon eväät ja miten sovellus muistuttaa, kun ne pitää syödä.",
        eyebrow="Eväät ilman ylimääräistä vaivaa",
        h1="Lounaseväät: ruokia, jotka kestävät eväinä, ja tapa muistaa ne",
        lead="Hyvät eväät syntyvät samasta ruoasta kuin päivällinen, vain tuplana. Vaikeinta ei ole kokkaaminen vaan se, että rasia jääkaapin perällä unohtuu. Tässä oppaassa on eväiksi sopivia ruokia, viikkorytmi ja turvallisuusohjeet.",
        sections=[
            ("Ruokia, jotka kestävät eväinä", """<p>Hyvät eväät kestävät päivän jääkaapissa ja muutaman minuutin mikrossa muuttumatta tylsiksi. Padat, curryt, chili, bulgur- ja riisisalaatit, lasagne, makaronilaatikko, pastavuoat ja uunijuurekset proteiinin kanssa ovat varmoja valintoja. Rapeat lisukkeet, tuore salaatti ja paistettu kananmuna kannattaa pakata erikseen ja lisätä vasta syödessä. Kun teet arkiruoasta tuplasatsin, eväät syntyvät ilman lisätyötä. Katso <a href="/fi/arkiruoka/">arkiruokaoppaasta</a>, mitkä ruoat sopivat tähän parhaiten.</p><ul><li><strong>Keitot</strong>: lohikeitto, linssikeitto, hernekeitto ja kanakeitto kestävät kuumentamisen hyvin.</li><li><strong>Laatikot</strong>: makaronilaatikko, kaalilaatikko ja kinkkukiusaus ovat usein parempia seuraavana päivänä.</li><li><strong>Padat ja curryt</strong>: riisin, bulgurin tai perunan kanssa, lisuke vaihtuu päivittäin.</li><li><strong>Viljapohjaiset salaatit</strong>: bulgur, ohra tai kvinoa, kasviksia ja proteiinia, kastike erikseen.</li></ul>"""),
            ("Suunnittele viikon eväät", """<ol><li>Valitse kaksi ruokaa, jotka kestävät eväinä, ja tee tuplasatsit sunnuntaina tai maanantaina.</li><li>Vaihtele lisukkeita: sama pata riisin kanssa yhtenä päivänä ja bulgurin ja jogurtin kanssa seuraavana.</li><li>Pakasta puolet heti. Jääkaapissa olevat eväät kannattaa syödä parin päivän sisällä; pakastetut säilyvät huomattavasti pidempään.</li><li>Kirjaa rasiat Cibellon ruokavarastoon, niin tiedät, mitä on ja mikä pitäisi syödä ensin.</li></ol><p>Kun tähteet on kirjattu eväinä Cibelloon, ne ovat mukana ruokavarastossa, kun seuraavan päivän ruokaa suunnitellaan. Tähteistä tulee osa <a href="/fi/ateriasuunnittelu/">viikkosuunnitelmaa</a> yllätyksen sijaan, ja ostoslistalle ei päädy aineksia ruokaan, jota ei tarvitse kokata.</p>"""),
            ("Pidä jääkaappi ja pakastin hallinnassa", """<p>Suurin osa kotitalouksien ruokahävikistä syntyy siitä, mikä unohtuu. Eväsrasia jääkaapin perimmäisessä nurkassa on klassikko. Cibellossa eväät voivat olla osa ruokavarastoasi, ja sovellus muistuttaa ystävällisesti, kun jokin pitäisi syödä. Jos et ole varma, kuinka kauan jokin säilyy, lue oppaamme <a href="/fi/parasta-ennen/">parasta ennen -päiväyksestä ja viimeisestä käyttöpäivästä</a>, ja luota aina hajuun, ulkonäköön ja maalaisjärkeen.</p>"""),
            ("Turvallisuus ja säilytys", """<ul><li>Jäähdytä ruoka nopeasti valmistuksen jälkeen ja laita se jääkaappiin parin tunnin sisällä.</li><li>Kuumenna eväät kunnolla, mieluiten niin, että ne höyryävät koko rasiasta.</li><li>Riisi ja pasta pitää jäähdyttää nopeasti ja syödä muutaman päivän sisällä.</li><li>Merkitse pakastetut rasiat sisällöllä ja päiväyksellä, tai anna sovelluksen pitää kirjaa.</li></ul><p>Sovelluksen päiväykset ja tekoälyn tulkinnat ovat tuki. Tarkista aina itse ennen syömistä, erityisesti kun ruoka on tarkoitettu lapsille, raskaana oleville tai henkilöille, joiden vastustuskyky on heikentynyt.</p>"""),
            ("Eväät, jotka eivät kyllästytä", """<p>Kyllästyminen on toiseksi yleisin syy siihen, että eväät jäävät syömättä. Ratkaisu on yksinkertainen: sama pohja, eri kuorrutus. Kanacurry riisillä maanantaina ja nuudelien kanssa keskiviikkona, chili riisin kanssa yhtenä päivänä ja tortillassa juuston kanssa toisena. Pieni purkki jogurttia, sitruunalohko, paahdetut siemenet tai tuoreet yrtit muuttavat saman ruoan uudeksi. Cibello ehdottaa reseptejä ruokavaraston perusteella, joten myös eväiden lisukkeet voi valita sen mukaan, mitä kaapissa jo on, ja se, mikä puuttuu, siirtyy <a href="/fi/ostoslista/">ostoslistaan</a>.</p>"""),
        ],
        faq=[
            ("Mitkä ruoat sopivat eväiksi?", "Padat, curryt, chili, laatikot, bulgur- tai riisisalaatit ja uunijuurekset proteiinin kanssa kestävät hyvin sekä jääkaapin että mikron."),
            ("Kuinka kauan eväät säilyvät jääkaapissa?", "Laske muutama päivä jääkaapissa ja huomattavasti pidempään pakastimessa. Jäähdytä nopeasti, kuumenna kunnolla ja tarkista aina haju ja ulkonäkö."),
            ("Voiko Cibello pitää kirjaa eväistäni?", "Kyllä. Eväät voi kirjata ruokavarastoon, ja sovellus muistuttaa, kun jokin pitäisi syödä."),
            ("Voivatko tähteet olla mukana suunnittelussa?", "Kyllä. Eväinä kirjatut tähteet näkyvät ruokavarastossa ja voidaan ottaa huomioon, kun seuraavan päivän ruokaa suunnitellaan."),
        ],
    ),

    "shopping-list": dict(
        slug="/fi/ostoslista/",
        label="Ostoslista",
        title="Ostoslista, joka täyttyy resepteistä | Cibello",
        desc="Jaettu ostoslista, joka sisältää vain sen, mikä oikeasti puuttuu: täyttyy resepteistä ja viikkosuunnitelmasta, näkyy koko taloudelle ja päivittää ruokavaraston kuitista.",
        eyebrow="Vain se, mikä puuttuu",
        h1="Ostoslista, joka täyttyy resepteistä ja näkyy koko taloudelle",
        lead="Tavallinen ostoslista kirjoitetaan muistista, ja siksi se on joko liian pitkä tai liian lyhyt. Ostoslista, joka lähtee ruokavarastosta ja suunnitelluista ruoista, sisältää vain sen, mikä oikeasti puuttuu.",
        sections=[
            ("Tavallisen ostoslistan ongelma", """<p>Useimmat ostoslistat kirjoitetaan muistista, usein yhden ihmisen toimesta, ja siksi ne ovat joko liian pitkiä (tuplaostoksia) tai liian lyhyitä (päivällisestä puuttuu jotakin). Ostoslistasovellukset ratkaisevat jakamisen, mutta eivät yhteyttä siihen, mitä kotona oikeasti on tai mitä aiotaan kokata. Lopputulos on, että lista vaatii edelleen jonkun, joka pitää kaiken päässään.</p><p>Tyypillinen esimerkki: kaupassa muistat, että kotona on ehkä kermaa. Ostat varmuuden vuoksi, ja jääkaapissa on sen jälkeen kaksi avattua purkkia, joista toinen menee hukkaan. Tai päinvastoin: lista on tehty huolella, mutta keskiviikon ruoasta puuttuu se yksi aines, jota kukaan ei muistanut kirjoittaa.</p>"""),
            ("Näin Cibellon ostoslista toimii", """<ol><li><strong>Lähtee ruokavarastosta.</strong> Kun suunnittelet ruoan, sen ainekset verrataan siihen, mitä jääkaapissa, pakastimessa ja kaapissa jo on. Vain puuttuvat lisätään listaan.</li><li><strong>Täyttyy viikkosuunnitelmasta.</strong> Kun suunnittelet viikon ruoat, kaikki täydennykset kootaan yhteen listaan.</li><li><strong>Jaetaan taloudelle.</strong> Kaikki talouden jäsenet näkevät saman listan ja voivat kuitata tuotteita kaupassa.</li><li><strong>Päivittää ruokavaraston.</strong> Kuvaa kuitti ostosten jälkeen, niin tuotteet kirjautuvat takaisin varastoon. Tarkista tunnistetut tuotteet, sillä tekoäly voi tulkita väärin.</li></ol><p>Voit tietenkin lisätä listalle myös asioita käsin: pesuainetta, kahvia tai sen, mitä ”pitää aina olla kotona”.</p>"""),
            ("Jaa ostoslista taloudessa", """<p>Cibellon taloustoiminto on tarkoitettu siihen, että useampi ihminen käyttää samaa ruokavarastoa, samaa <a href="/fi/ateriasuunnittelu/">viikkosuunnitelmaa</a> ja samaa ostoslistaa. Kotimatkalla oleva näkee, mitä puuttuu, eikä suunnittelijan tarvitse lähettää listaa erikseen viestillä. Kokeilujakson aikana ja sen jälkeen maksullisella tilauksella talous saa yhteisen näkymän. Sovellus on tarkoitettu 18 vuotta täyttäneille, ja tiedot tallennetaan EU:n alueella.</p>"""),
            ("Ostoslista, joka vähentää hävikkiä ja kuluja", """<p>Kun lista sisältää vain sen, mikä puuttuu, useimmat tuplaostokset jäävät pois, ja kun pian vanhenevat ainekset suunnitellaan käyttöön ensin, hävikki pienenee. Periaate on sama kuin oppaassa <a href="/fi/vahenna-ruokahavikkia/">ruokahävikin vähentämisestä</a>: yleiskuva ennen ostoksia. Samalla säästät aikaa. Yksi kauppareissu viikossa ja pari täydennystä riittää useimmille talouksille, kun lista on kunnossa ja perustuu siihen, mitä oikeasti aiotaan kokata.</p>"""),
            ("Vinkkejä parempaan kauppareissuun", """<ul><li>Pidä ruokavarasto ajan tasalla: kuvaa kuitti heti ostosten jälkeen, niin lista on seuraavalla kerralla tarkka.</li><li>Suunnittele 3–5 ruokaa kerralla, niin lista on yhden reissun kokoinen.</li><li>Lisää vakiotuotteet listalle käsin, jos niitä ei tule resepteistä.</li><li>Silmäile jääkaapin avatut pakkaukset ennen kauppaa: sovellus näyttää ne, mutta katse ei koskaan ole turha.</li><li>Katso <a href="/fi/reseptit-aineksista/">reseptit aineksista</a>, jos haluat käyttää ensin sen, mikä jo on kotona, ja ostaa vähemmän.</li></ul>"""),
        ],
        faq=[
            ("Näkeekö koko talous saman ostoslistan?", "Kyllä. Cibellon taloustoiminto jakaa ruokavaraston, viikkosuunnitelman ja ostoslistan jäsenten kesken."),
            ("Täyttyykö ostoslista automaattisesti?", "Kyllä. Kun suunnittelet reseptejä tai viikkosuunnitelman, ruokavarastosta puuttuvat ainekset lisätään listalle."),
            ("Voinko lisätä listalle omia tuotteita?", "Kyllä, kaiken voi lisätä käsin, myös muun kuin ruoan."),
            ("Päivittyykö ruokavarasto, kun olen käynyt kaupassa?", "Voit kuvata kuitin tai skannata viivakoodit, jolloin tuotteet lisätään ruokavarastoon. Tarkista tulos, sillä tekoäly voi tulkita väärin."),
        ],
    ),

    "best-before": dict(
        slug="/fi/parasta-ennen/",
        label="Parasta ennen",
        title="Parasta ennen vai viimeinen käyttöpäivä? | Cibello",
        desc="Parasta ennen -päiväys kertoo laadusta, viimeinen käyttöpäivä turvallisuudesta. Näin tulkitset päiväykset, kuinka kauan ruoat säilyvät ja miten pysyt niistä kärryillä.",
        eyebrow="Päiväykset selkokielellä",
        h1="Parasta ennen ja viimeinen käyttöpäivä: mitä päiväykset oikeasti tarkoittavat",
        lead="Kaksi päiväystä, kaksi eri asiaa. Parasta ennen on laatulupaus, viimeinen käyttöpäivä on turvallisuusraja. Kun eron ymmärtää, hävikkiä syntyy vähemmän eikä riskejä oteta turhaan.",
        sections=[
            ("Parasta ennen: laaturaja", """<p><strong>Parasta ennen</strong> kertoo, kuinka kauan valmistaja lupaa tuotteen täyden laadun: maun, rakenteen ja ravintoarvon. Päiväyksen jälkeen tuote on usein edelleen syötävää, kunhan se on säilytetty oikein ja pakkaus on avaamaton. Tämä koskee esimerkiksi maitoa, jogurttia, kananmunia, kovia juustoja, säilykkeitä, kuivatuotteita ja pakasteita. Katso, haista ja maista: Ruokaviraston ohjeiden mukaan se on hyvä tapa arvioida, onko ruoka syötävää parasta ennen -päiväyksen jälkeen. Päiväysmerkinnät perustuvat EU:n yhteiseen lainsäädäntöön, joten sama logiikka pätee kaikissa jäsenmaissa, vaikka sanamuodot vaihtelevat kielittäin.</p>"""),
            ("Viimeinen käyttöpäivä: turvallisuusraja", """<p><strong>Viimeinen käyttöpäivä</strong> (pakkauksessa usein muodossa ”viimeinen käyttöajankohta”) on herkästi pilaantuvien tuotteiden merkintä. Niissä bakteerit voivat lisääntyä ilman, että ruoka haisee tai näyttää pilaantuneelta: tuore broileri, jauheliha, tuore kala ja osa valmisruoista. Tämän päiväyksen jälkeen tuotetta ei pidä syödä. Turvallisinta on kypsentää tai pakastaa tuote viimeistään päiväyksen päivänä. Pakastaminen pysäyttää kellon, ja pakastetun tuotteen voi kypsentää sulatuksen jälkeen.</p>"""),
            ("Kuinka kauan tavalliset ruoat säilyvät?", """<div class="table-wrap"><table class="cmp"><caption>Suuntaa antavia säilyvyysaikoja parasta ennen -päiväyksen jälkeen</caption><thead><tr><th scope="col">Elintarvike</th><th scope="col">Suuntaa antava aika päiväyksen jälkeen (avaamaton, oikein säilytetty)</th><th scope="col">Huomio</th></tr></thead><tbody><tr><th scope="row">Maito ja piimä</th><td>Muutama päivä, jopa viikko</td><td>Haista ja maista; hapantunut maito huomaa selvästi</td></tr><tr><th scope="row">Jogurtti ja rahka</th><td>Usein viikosta useaan viikkoon</td><td>Happamuus suojaa; tarkista home</td></tr><tr><th scope="row">Kananmunat</th><td>Useita viikkoja</td><td>Jos muna kelluu vedessä, heitä se pois</td></tr><tr><th scope="row">Kova juusto</th><td>Viikkoja tai kuukausia</td><td>Leikkaa pintahome pois kovasta juustosta</td></tr><tr><th scope="row">Säilykkeet ja kuivatuotteet</th><td>Kuukausia tai vuosia</td><td>Hävitä lommoiset tai pullistuneet tölkit</td></tr><tr><th scope="row">Pakasteet</th><td>Kuukausia</td><td>Laatu heikkenee, turvallisuus säilyy</td></tr><tr><th scope="row">Kypsennetty jauheliha, broileri</th><td>2–3 päivää jääkaapissa</td><td>Kypsennetty ruoka: jäähdytä nopeasti, kuumenna kunnolla</td></tr><tr><th scope="row">Keitetty riisi ja pasta</th><td>Muutama päivä jääkaapissa</td><td>Jäähdytä nopeasti keittämisen jälkeen</td></tr></tbody></table></div><p>Taulukko on suuntaa antava. Noudata aina pakkauksen ohjeita ja omia aistejasi, ja ole erityisen tarkka ruoasta, joka on tarkoitettu lapsille, raskaana oleville tai henkilöille, joiden vastustuskyky on heikentynyt.</p>"""),
            ("Miksi päiväykset menevät sekaisin", """<p>Kotitalouksissa heitetään pois paljon ruokaa, joka olisi ollut täysin syötävää, koska parasta ennen -päiväys luetaan turvallisuusrajana. Toisaalta viimeinen käyttöpäivä ohitetaan joskus ajatuksella ”kyllä se vielä kestää”, vaikka juuri siinä riski on todellinen. Nyrkkisääntö on yksinkertainen: parasta ennen -tuotteiden kohdalla luota aisteihisi, viimeisen käyttöpäivän tuotteiden kohdalla luota päiväykseen. Avattu pakkaus on oma lukunsa: sen jälkeen päiväys ei enää päde, vaan ratkaisee, kuinka kauan pakkaus on ollut auki ja miten se on säilytetty. Lisää käytännön keinoja löydät oppaasta <a href="/fi/vahenna-ruokahavikkia/">vähennä ruokahävikkiä</a>.</p>"""),
            ("Näin pysyt päiväyksistä kärryillä", """<p>Vaikeinta eivät ole säännöt vaan muistaminen. Cibellossa tuotteet ovat ruokavarastossasi päiväyksineen, kuiteista, viivakoodeista tai kuvaamistasi tuotteista, ja sovellus huomauttaa ystävällisesti, kun jokin pitäisi käyttää pian. <a href="/fi/reseptit-aineksista/">Reseptiehdotukset</a> nostavat silloin ylimmäksi ruoat, joissa juuri ne tuotteet käytetään. Näin hävikin vähentäminen on päivällisen sivutuote, ei erillinen projekti. Tekoäly voi tulkita päiväyksen väärin, joten tarkista aina itse. Samat päiväykset auttavat myös <a href="/fi/lounasevaat/">eväiden</a> kanssa: rasia, joka on kirjattu varastoon, ei unohdu.</p>"""),
        ],
        faq=[
            ("Mitä eroa on parasta ennen -päiväyksellä ja viimeisellä käyttöpäivällä?", "Parasta ennen on laaturaja: tuote on usein syötävää sen jälkeenkin, jos se on säilytetty oikein. Viimeinen käyttöpäivä on turvallisuusraja herkille tuotteille, kuten broilerille ja jauhelihalle, eikä sitä pidä ylittää."),
            ("Voiko ruokaa syödä parasta ennen -päiväyksen jälkeen?", "Usein kyllä. Katso, haista ja maista. Tämä ei koske tuotteita, joissa on viimeinen käyttöpäivä."),
            ("Kuinka kauan maito säilyy parasta ennen -päiväyksen jälkeen?", "Usein muutaman päivän, jopa viikon, jos pakkaus on ollut avaamaton ja kylmässä. Haju ja maku ratkaisevat."),
            ("Voiko sovellus muistuttaa ennen kuin ruoka pilaantuu?", "Kyllä. Cibello pitää päiväykset ruokavarastossa, muistuttaa, kun jokin pitäisi käyttää, ja ehdottaa reseptejä, joissa tuote käytetään. Tarkista päiväykset aina itse."),
        ],
    ),

    "weekday-dinners": dict(
        slug="/fi/ruokaideoita-arkeen/",
        label="Ruokaideoita arkeen",
        title="25 ruokaideaa arkeen, ajan mukaan järjestettynä | Cibello",
        desc="25 arkiruokaa 15, 25 ja 30 minuutin listoina, kotona yleensä olevista aineksista. Lisäksi tapa antaa jääkaapin valita, kun inspiraatio on lopussa.",
        eyebrow="Arki-illan ruokaideat",
        h1="Ruokaideoita arkeen: 25 ruokaa ajan mukaan järjestettynä",
        lead="Arki-iltana kysymys ei ole, mikä olisi hienoin ruoka, vaan mikä valmistuu siinä ajassa, joka on, niistä aineksista, jotka on. Tässä on 25 ruokaa kolmessa aikaluokassa ja niksi, jolla listaa ei tarvitse selata joka ilta.",
        sections=[
            ("Valmista 15 minuutissa", """<ul><li><strong>Tonnikalapasta</strong>: pasta, tonnikala, ranskankerma, sitruuna.</li><li><strong>Paistettu riisi</strong>: keitetty riisi, kananmuna, pakastevihannekset, soija.</li><li><strong>Tortillapizza</strong>: tortilla, tomaattikastike, juusto ja se, mitä löytyy.</li><li><strong>Pestopasta kanalla</strong>: eilisen kanaa tai valmiiksi grillattua.</li><li><strong>Munakas juustolla ja kasviksilla</strong>: pelastaa kananmunat ja puolikkaat kasvikset.</li><li><strong>Halloumiwrapit</strong>: halloumi, tortilla, salaatti, jogurttikastike.</li><li><strong>Katkarapuleivät</strong>: paahtoleipä, katkaravut, kananmuna, majoneesi.</li></ul>"""),
            ("Valmista 20–25 minuutissa", """<ul><li><strong>Nakkikastike ja perunamuusi</strong>.</li><li><strong>Kanawokki nuudeleilla</strong>.</li><li><strong>Tacot</strong> jauhelihalla, kanalla tai pavuilla.</li><li><strong>Pasta carbonara</strong>.</li><li><strong>Uunilohi perunoiden ja sitruunan kanssa</strong>.</li><li><strong>Falafelit pitaleivässä</strong>.</li><li><strong>Tomaattikeitto ja juustoleivät</strong>.</li><li><strong>Kikhernepata pinaatilla</strong>.</li><li><strong>Pyttipannu tähteistä</strong>.</li><li><strong>Lohipoke riisillä ja avokadolla</strong>.</li></ul>"""),
            ("Valmista 30 minuutissa", """<ul><li><strong>Kermainen kanakastike sienillä</strong>.</li><li><strong>Linssikeitto ja leipä</strong>.</li><li><strong>Chili sin carne</strong>.</li><li><strong>Kanacurry kookosmaidolla</strong>: tee tuplasatsi eväiksi.</li><li><strong>Lihapullat ja perunamuusi</strong>.</li><li><strong>Uunipelti nakeista ja juureksista</strong>.</li><li><strong>Lohikeitto</strong>.</li><li><strong>Papupihvit ja perunat</strong>.</li></ul><p>Lisää nopeita ruokia, taulukon kera ajasta ja aineksista, on oppaassa <a href="/fi/nopea-ruoka/">nopea ruoka 20–30 minuutissa</a>. Jos pöydässä on lapsia: <a href="/fi/lapsiperheen-ruoka/">lapsiperheen ruokaideat</a>. Ja jos haluat ruokia, jotka riittävät myös seuraavan päivän lounaaksi, katso <a href="/fi/lounasevaat/">lounaseväät</a>.</p>"""),
            ("Niksi: anna jääkaapin valita", """<p>Kaikki yllä olevat ruoat edellyttävät, että ainekset oikeasti ovat kotona. Siihen arkiruoka yleensä kaatuu: valitaan ensin ruoka ja huomataan sitten, että paprika on loppu. Cibello kääntää järjestyksen. Kuvaa jääkaappi ja kaapit, niin sovellus tietää, mitä on, ja <a href="/fi/reseptit-aineksista/">reseptiehdotukset</a> järjestetään sen mukaan, kuinka suuri osa aineksista sinulla on, pian vanhenevat ylimpänä. Tunnistetut tuotteet tarkistat itse ennen tallennusta, sillä tekoäly voi erehtyä. Neljästä arkipäivästä syntyy <a href="/fi/ateriasuunnittelu/">viikkosuunnitelma</a>, ja puuttuvat ainekset menevät jaettuun <a href="/fi/ostoslista/">ostoslistaan</a>.</p>"""),
            ("Kierto voittaa inspiraation", """<p>Useimmat taloudet syövät 10–15 ruokaa kierrossa, eikä siinä ole mitään vikaa. Vaihtelun niksi on vaihtaa proteiinia ja lisuketta, ei koko ruokaa: sama pata kanalla yhtenä viikkona ja kikherneillä seuraavana, samat tacot kalalla jauhelihan sijaan, sama keitto perunalla tai ohralla. Cibello oppii, mitä teillä yleensä valitaan, ja ehdottaa versioita, jotka muistuttavat suosikkejanne mutta käyttävät sitä, mitä kotona juuri nyt on. <a href="/fi/arkiruoka/">Lue lisää arkiruoasta, joka kantaa koko viikon</a>.</p>"""),
            ("Kun et jaksa edes valita listalta", """<p>Joskus 25 vaihtoehtoa on liikaa. Silloin auttaa sattuma: <a href="/fi/mita-tanaan-syotaisiin/">ruokavalitsin</a> arpoo ehdotuksen proteiinin, ajan ja tilanteen mukaan, ilman tiliä. Ja jos haluat, että ehdotus perustuu siihen, mitä jääkaapissasi todella on, sovellus tekee sen puolestasi ja kertoo samalla, miksi juuri tämä ruoka: koska kerma vanhenee pian tai koska kaikki ainekset ovat jo kotona.</p>"""),
        ],
        faq=[
            ("Mitkä ovat hyviä ruokaideoita arkeen?", "Ruoat, jotka valmistuvat 15–30 minuutissa kotona yleensä olevista aineksista: pasta, munakas, wokki, tacot, keitot, padat ja uunipeltiruoat. Yllä olevassa listassa on 25 tällaista ruokaa."),
            ("Miten löydän ruokaideoita siitä, mitä kotona on?", "Kuvaa jääkaappi ja kaapit Cibellossa. Sovellus järjestää yli 9 000 reseptiä sen mukaan, kuinka suuri osa aineksista on jo kotona."),
            ("Miten saan vaihtelua arkiruokaan?", "Vaihda proteiinia ja lisukkeita koko ruoan sijaan, suunnittele kolme tai neljä päivällistä kerralla ja lisää yksi tähdepäivä."),
            ("Pitääkö minun kokata joka ilta?", "Ei. Tuplasatsi kahdesta ruoasta viikossa kattaa usein kaksi muuta iltaa eväinä tai tähteinä. Cibellossa tähteet voi kirjata ruokavarastoon, jolloin ne näkyvät suunnittelussa."),
        ],
    ),

    "what-to-eat-tonight": dict(
        slug="/fi/mita-tanaan-syotaisiin/",
        label="Mitä tänään syötäisiin",
        title="Mitä tänään syötäisiin? Ruokavalitsin ja vinkit | Cibello",
        desc="Mitä tänään syötäisiin? Arvo ruoka valitsimella proteiinin, ajan ja tilanteen mukaan, tai anna sovelluksen ehdottaa sen perusteella, mitä jääkaapissasi on.",
        eyebrow="Illan ikuinen kysymys",
        h1="Mitä tänään syötäisiin? Vastaus kymmenessä sekunnissa",
        lead="Kysymys toistuu joka ilta, ja siihen vastaaminen on yllättävän raskasta: mitä on, paljonko aikaa on, kuka syö ja mikä pitäisi käyttää ensin. Arvo ruoka alla olevalla valitsimella tai lue, miten kysymyksestä pääsee kokonaan eroon.",
        sections=[
            ("Miksi ruokakysymys on niin vaikea", """<p>Päätös siitä, mitä kokata, tarkoittaa neljän asian jonglöörausta yhtä aikaa: mitä kotona on, paljonko aikaa on, mitä kaikki suostuvat syömään ja mikä pitäisi käyttää ennen kuin se pilaantuu. Sen tekeminen päässä joka ilta on oikeaa kuormaa. Useimmat päätyvät samaan kolmeen ruokaan tai noutoruokaan, eivät ideoiden puutteen vuoksi vaan siksi, että päättäminen väsyttää.</p>"""),
            ("Kolme kysymystä, jotka antavat vastauksen", """<ol><li><strong>Mitä kotona on, mikä pitäisi käyttää?</strong> Aloita jääkaapista, älä reseptikirjasta. Pian vanheneva ohjaa valintaa.</li><li><strong>Paljonko aikaa ja jaksamista on?</strong> Alle 20 minuuttia: pasta, munakas, wokki, wrapit. Enemmän aikaa: pata, uunipelti, keitto.</li><li><strong>Kuka syö?</strong> Lapset, vieraat tai vain sinä ratkaisevat, kuinka tuttua tai kunnianhimoista saa olla.</li></ol><p>Cibello esittää nämä kolme kysymystä puolestasi: sovellus tietää, mitä sinulla on, sinä valitset ajan ja seuran, ja ehdotukset tulevat selityksen kanssa, esimerkiksi ”koska sinulla on kanaa ja kermaa, jotka vanhenevat pian”. Lue lisää <a href="/fi/nopea-ruoka/">nopeasta ruoasta 20–30 minuutissa</a> ja <a href="/fi/ruokaideoita-arkeen/">ruokaideoista arkeen</a>.</p>"""),
            ("Mitä tehdä, kun kotona ei ole mitään?", """<p>Sinulla on lähes aina enemmän kuin luulet. Pasta, riisi tai ohra, kananmunat, tölkki tomaattimurskaa, purkki papuja, sipuli, pakastevihannekset ja juusto riittävät vähintään viiteen päivälliseen: tomaattipasta pavuilla, munakas, paistettu riisi, linssikeitto ja tortillapizza. Cibelloon kirjattu ruokavarasto näyttää lisäksi tarkalleen, mitä on, myös sen, mikä on unohtunut kaapin perälle. <a href="/fi/reseptit-aineksista/">Reseptit aineksista</a> kertoo, miten haku toimii.</p>"""),
            ("Mitä tarjota vieraille?", """<p>Vieraiden kanssa pätevät eri säännöt: valitse jotakin, jonka voi valmistaa etukäteen (pata, lasagne, uunibroileri), joka sietää odottamista ja jonka olet tehnyt ennenkin. Käytä aika lisukkeisiin. Jos suunnittelet jo viikon aikana, puuttuvat ainekset menevät <a href="/fi/ostoslista/">ostoslistaan</a>, ja tähteistä tulee maanantain <a href="/fi/lounasevaat/">eväät</a>.</p>"""),
            ("Jääkaappi ensin, resepti sitten", """<p>Cibello kääntää tavallisen järjestyksen. Kuvaa jääkaappi, pakastin ja kaapit tai skannaa kuitti, niin sovellus rakentaa ruokavaraston. Kun kysyt ”mitä syötäisiin”, sovellus vertaa varastoa yli 9 000 reseptiin ja järjestää ne sen mukaan, kuinka paljon sinulla jo on kotona: ruoka, jonka aineksista 90 prosenttia on keittiössäsi, tulee ensimmäisenä. Ehdotukset painottavat myös pian vanhenevia tuotteita ja sitä, mistä taloudessa yleensä pidetään. Tekoäly voi tulkita kuvat väärin, joten tarkistat tunnistetut tuotteet ennen tallennusta, ja allergiasuodattimet ovat ohjeellisia, eivät takuu.</p>"""),
            ("Pääse kysymyksestä kokonaan eroon", """<p>Se, joka suunnittelee kolme tai viisi päivällistä kerralla, ei koskaan seiso jääkaapin edessä kello 17. <a href="/fi/ateriasuunnittelu/">Viikkosuunnitelma</a>, jossa ruoat käyttävät ainekset oikeassa järjestyksessä, jaettu ostoslista ja ystävälliset muistutukset ennen kuin jokin pilaantuu, poistavat sekä päätöksen että hävikin. Juuri sitä Cibello tekee. Sovellus on tarkoitettu aikuisille, ja 14 päivän kokeilujakso ei vaadi korttia. Jos haluat lukea taustaa, <a href="/fi/arkiruoka/">arkiruokaopas</a> kertoo, miten viikko rakennetaan niin, että se kestää.</p>"""),
        ],
        faq=[
            ("Mitä syödä, kun ei ole yhtään inspiraatiota?", "Käytä yllä olevaa ruokavalitsinta tai lähde siitä, mitä kotona on: pasta, munakas, wokki, tacot, keitto tai uunipelti kattavat useimmat illat. Cibello ehdottaa ruokia ruokavarastosi perusteella."),
            ("Mitä tänään syötäisiin kasvisruokaa?", "Linssikeitto, chili sin carne, kikhernepata, papupihvit, halloumisalaatti, pastavuoka parsakaalilla tai falafelit pitassa. Kaikki valmistuvat alle 30 minuutissa kaapin aineksista."),
            ("Mitä kokata siitä, mitä kotona on?", "Kirjaa jääkaappi ja kaapit Cibelloon kuvaamalla ne. Sovellus järjestää yli 9 000 reseptiä sen mukaan, kuinka suuri osa aineksista sinulla jo on."),
            ("Miten lopetan ruoan miettimisen joka päivä?", "Suunnittele kolme tai viisi päivällistä kerralla viikkosuunnitelmaan, anna ostoslistan täyttyä automaattisesti ja käytä pian vanhenevat ainekset ensin."),
        ],
    ),
}

TOOL = dict(
    heading="Ruokavalitsin: ehdotus kymmenessä sekunnissa",
    protein_label="Proteiini", time_label="Aika", mode_label="Tilanne",
    protein={"any": "Mikä tahansa", "chicken": "Kana", "meat": "Liha", "fish": "Kala", "veg": "Kasvis"},
    time={"20": "Enintään 20 min", "30": "Enintään 30 min", "45": "Enintään 45 min", "90": "Ei väliä"},
    mode={"all": "Kaikki", "quick": "Nopeasti", "leftovers": "Käytä tähteet", "pantry": "Kaapin aineksista", "budget": "Edullisesti", "kids": "Lapsille sopiva", "mealbox": "Riittää eväiksi", "friday": "Perjantaiherkku"},
    button="Arvo ruoka",
    no_match="Mikään ei osunut. Kokeile löysätä jotakin suodatinta.",
    minutes="min",
    any_protein="mikä tahansa proteiini",
    tip="Onko ainekset jo kotona? Sovelluksessa ehdotukset lähtevät siitä, mitä jääkaapissasi oikeasti on.",
    note="Valitsin arpoo neljänkymmenen arkiruoan joukosta eikä vaadi tiliä. Sovelluksessa ehdotukset perustuvat siihen, mitä jääkaapissasi todella on.",
    dishes=[
        ("Lohikeitto", "fish", 30, ["kids", "friday"]),
        ("Makaronilaatikko", "meat", 45, ["kids", "mealbox", "budget"]),
        ("Lihapullat ja perunamuusi", "meat", 30, ["kids"]),
        ("Jauhelihakastike ja spagetti", "meat", 25, ["kids", "budget", "mealbox"]),
        ("Hernekeitto ja pannukakku", "meat", 30, ["pantry", "budget"]),
        ("Pinaattiletut ja puolukkahillo", "veg", 25, ["kids", "budget"]),
        ("Uunilohi ja perunat", "fish", 30, ["kids", "friday"]),
        ("Kalapuikot ja perunamuusi", "fish", 20, ["kids", "quick"]),
        ("Broilerikastike ja riisi", "chicken", 25, ["kids", "mealbox"]),
        ("Pestopasta kanalla", "chicken", 15, ["quick", "kids"]),
        ("Nakkikastike ja perunat", "meat", 25, ["kids", "budget"]),
        ("Pyttipannu tähteistä", "any", 20, ["leftovers", "budget"]),
        ("Lohipasta tillillä", "fish", 20, ["quick", "friday"]),
        ("Tonnikalapasta", "fish", 15, ["pantry", "quick", "budget"]),
        ("Kasvissosekeitto ja leipä", "veg", 30, ["leftovers", "budget"]),
        ("Linssikeitto", "veg", 30, ["pantry", "budget", "mealbox"]),
        ("Chili sin carne", "veg", 30, ["pantry", "mealbox", "budget"]),
        ("Kasviscurry kookosmaidolla", "veg", 25, ["pantry", "mealbox"]),
        ("Kanawokki nuudeleilla", "chicken", 20, ["quick", "leftovers"]),
        ("Paistettu riisi kananmunalla ja pakastevihanneksilla", "veg", 15, ["leftovers", "quick", "budget"]),
        ("Tortillapizza jääkaapin aineksista", "any", 15, ["leftovers", "quick", "kids"]),
        ("Tacot jauhelihalla, kanalla tai pavuilla", "any", 20, ["kids", "friday"]),
        ("Hampurilaiset ja lohkoperunat", "meat", 35, ["friday", "kids"]),
        ("Kotipizza", "any", 45, ["friday", "kids"]),
        ("Uunimakkara ja juurekset", "meat", 30, ["budget", "kids"]),
        ("Kaalilaatikko", "meat", 60, ["mealbox", "budget"]),
        ("Lasagne (tuplasatsi eväiksi)", "meat", 60, ["mealbox", "kids"]),
        ("Kanacurry kookosmaidolla ja riisi", "chicken", 30, ["mealbox", "leftovers"]),
        ("Munakas jääkaapin tähteistä", "veg", 15, ["leftovers", "budget", "quick"]),
        ("Bulgursalaatti halloumilla tai kanalla", "any", 20, ["quick", "mealbox"]),
        ("Falafelit pitaleivässä", "veg", 20, ["quick", "budget"]),
        ("Papupihvit ja perunat", "veg", 30, ["budget", "kids"]),
        ("Kasvislasagne", "veg", 50, ["mealbox", "friday"]),
        ("Silakkapihvit ja perunamuusi", "fish", 30, ["budget"]),
        ("Kesäkeitto", "veg", 30, ["kids", "budget"]),
        ("Kinkkukiusaus", "meat", 45, ["mealbox", "leftovers"]),
        ("Katkarapupasta sitruunalla ja valkosipulilla", "fish", 20, ["quick", "friday"]),
        ("Broileriwrapit jogurttikastikkeella", "chicken", 20, ["quick", "kids"]),
        ("Sitruunainen uunibroileri ja juurekset", "chicken", 45, ["friday"]),
        ("Tomaattipasta pavuilla tai jauhelihalla", "any", 20, ["pantry", "budget", "kids"]),
    ],
)
