"""Polish (pl), phase 2, file A: everyday-food, quick-dinner, family-dinner, meal-boxes,
shopping-list, best-before, weekday-dinners, what-to-eat-tonight, plus TOOL."""

LANG = "pl"

GUIDES2 = {
    "everyday-food": dict(
        slug="/pl/domowe-obiady/",
        label="Domowe obiady",
        title="Domowe obiady na co dzień: proste przepisy | Cibello",
        desc="Domowe obiady na co dzień, które da się ugotować po pracy z tego, co masz w lodówce. Jak zaplanować tydzień, zmieniać dania i wyrzucać mniej.",
        eyebrow="Poradnik",
        h1="Domowe obiady na co dzień, które da się ugotować po pracy",
        lead="Dobry obiad w tygodniu nie wymaga nowego przepisu każdego dnia. Wymaga produktów, które masz, czasu, który realnie jest, i odrobiny planu. Pokazujemy, jak to ustawić raz i mieć spokój do niedzieli.",
        sections=[
            ("Co to znaczy dobry obiad na co dzień?",
             """<p>Dobry codzienny obiad ma trzy cechy. Da się go zrobić w czasie, który naprawdę masz, a nie w tym, który wpisano w przepisie. Opiera się na produktach, które już leżą w lodówce albo które kupisz bez nadkładania drogi. I daje się zmieniać, żeby nikt w domu nie jęknął, że znowu to samo. Rzadko chodzi o nowe przepisy. Większość domów gotuje w kółko 10 do 15 dań i to jest zupełnie w porządku. Różnica między nerwowym a spokojnym gotowaniem w tygodniu prawie nigdy nie leży w umiejętnościach kulinarnych. Leży w tym, czy wiesz, co masz w domu i co z tego zrobisz.</p>"""),
            ("Przepisy na obiad, które zaczynają się w lodówce",
             """<p>Większość serwisów z przepisami działa od złej strony: najpierw wybierasz danie, a potem odkrywasz, że brakuje ci połowy składników. Cibello odwraca kolejność. Robisz zdjęcie lodówki, zamrażarki i spiżarni albo skanujesz paragon, a aplikacja rozpoznaje produkty i buduje z nich twój domowy spis. Potem porównuje ten spis z ponad 9 000 przepisów i pokazuje, jaki procent składników masz już u siebie. Dania, do których masz 80 do 100 procent produktów, lądują na górze. Dzięki temu <a href="/pl/przepisy-z-produktow/">przepisy z produktów, które masz</a>, dają się ugotować dziś wieczorem, a nie tylko ładnie wyglądają.</p><ul><li><strong>Makaron i kasze</strong>: prawie zawsze coś jest w szafce, reszta dobiera się z lodówki.</li><li><strong>Jajka</strong>: omlet, jajecznica, szakszuka i naleśniki ratują jajka, mleko i warzywa z krótkim terminem.</li><li><strong>Zupy i gulasze</strong>: przyjmują resztki i następnego dnia stają się <a href="/pl/meal-prep/">obiadem do pudełka</a>.</li><li><strong>Patelnia z ryżem lub kaszą</strong>: wykorzystuje połówki warzyw i ugotowane wczoraj dodatki.</li><li><strong>Blacha z piekarnika</strong>: ziemniaki, warzywa korzeniowe, kurczak lub ryba, minimum pracy.</li><li><strong>Pierogi, kopytka, kluski</strong>: z zamrażarki albo z resztek ziemniaków, u dzieci prawie zawsze na tak.</li></ul>"""),
            ("Obiady na cały tydzień, nie na jeden wieczór",
             """<p>Jeśli planujesz pięć dni naraz, każdy pojedynczy wieczór staje się prostszy. Dobry <a href="/pl/planer-posilkow/">plan posiłków na tydzień</a> bierze pod uwagę, kiedy masz czas, co trzeba zużyć najpierw i które dania zostawią porcję na jutro. Cibello zmienia produkty i typy dań, żeby to samo nie wracało dwa dni z rzędu, a to, czego brakuje, zbiera na <a href="/pl/lista-zakupow/">wspólnej liście zakupów</a>. Plan przeglądasz i poprawiasz, zanim tydzień się zacznie. Propozycje są pomocą, nie obowiązkiem.</p>"""),
            ("Szybko, tanio i tak, żeby dzieci zjadły",
             """<p>W jednym tygodniu liczy się czas, w innym budżet, a w kolejnym to, czy dzieci w ogóle usiądą do stołu. Kiedy brakuje czasu, punktem wyjścia jest <a href="/pl/szybki-obiad/">szybki obiad w 20 do 30 minut</a>. Kiedy przy stole są dzieci, pomogą <a href="/pl/obiady-dla-rodziny/">pomysły na obiady dla rodziny</a>, które maluchy znają i akceptują. Cibello wychodzi od tego, co masz w domu, od alergii i nawyków żywieniowych, a z czasem uczy się, co u was zwykle wygrywa. Filtry alergenów traktuj jako wskazówkę, nie gwarancję, i zawsze sprawdzaj skład na opakowaniu.</p>"""),
            ("Jak sprawić, żeby domowe obiady przetrwały dłużej niż tydzień",
             """<ol><li>Zarejestruj to, co masz w domu, raz, a potem aktualizuj przy zakupach, na przykład zdjęciem paragonu.</li><li>Niech propozycje wychodzą ze spisu produktów, a nie z pustej głowy o siedemnastej.</li><li>Planuj trzy do pięciu obiadów naraz, nie siedem. Zostaw miejsce na resztki i spontaniczność.</li><li>Gotuj podwójną porcję dań, które to lubią, i mroź w pudełkach.</li><li>Sprawdzaj składniki, alergeny i daty samodzielnie. Aplikacja jest wsparciem, a AI może się pomylić przy rozpoznawaniu produktów, dlatego wynik skanu zawsze przeglądasz przed zapisaniem.</li></ol>"""),
            ("Resztki to nie problem, to obiad na jutro",
             """<p>Największa część jedzenia wyrzucanego w domach to rzeczy, o których zapomniano: pół słoika śmietany, dwie marchewki, wczorajszy ryż. Kiedy spis produktów w Cibello jest aktualny, aplikacja delikatnie przypomina, że coś warto zjeść w najbliższych dniach, a propozycje dań stawiają te produkty wyżej. Tak <a href="/pl/ograniczanie-marnowania-zywnosci/">ograniczanie marnowania żywności</a> dzieje się przy okazji gotowania obiadu, bez osobnego wysiłku. Więcej o terminach na opakowaniach znajdziesz w poradniku <a href="/pl/najlepiej-spozyc-przed/">najlepiej spożyć przed a należy spożyć do</a>.</p>"""),
        ],
        faq=[
            ("Co to są domowe obiady na co dzień?", "To dania, które da się ugotować w zwykły dzień po pracy: szybkie, z produktów, które masz w domu lub łatwo dokupisz, i na tyle elastyczne, żeby zmieniać je w ciągu tygodnia."),
            ("Jak znaleźć przepis na obiad z tego, co mam w lodówce?", "W Cibello robisz zdjęcie lodówki, zamrażarki i spiżarni albo skanujesz paragon. Aplikacja porównuje twoje produkty z ponad 9 000 przepisów i pokazuje, jaki procent składników już masz."),
            ("Czy Cibello zaplanuje obiady na cały tydzień?", "Tak. Cibello proponuje plan tygodnia, który zmienia dania i produkty, a brakujące składniki zbiera na wspólnej liście zakupów. Plan przeglądasz i zmieniasz samodzielnie."),
            ("Czy propozycje uwzględniają alergie?", "Możesz podać alergie i nawyki żywieniowe, ale filtrowanie to wskazówka, nie gwarancja. Zawsze sprawdzaj skład i opakowanie samodzielnie."),
        ],
    ),

    "quick-dinner": dict(
        slug="/pl/szybki-obiad/",
        label="Szybki obiad",
        title="Szybki obiad w 30 minut z tego, co masz w domu | Cibello",
        desc="Szybki obiad w 20 do 30 minut bez wyjścia do sklepu: tabela dań, które prawie zawsze da się zrobić, i sposób na propozycję z lodówki w minutę.",
        eyebrow="Poradnik",
        h1="Szybki obiad w 20 do 30 minut z tego, co masz w domu",
        lead="Szybki obiad psuje się zwykle nie na patelni, tylko wcześniej: brakuje jednej rzeczy i 20 minut zamienia się w 50 z wyjściem do sklepu. Oto dania, które prawie zawsze da się zrobić, i sposób, żeby propozycja pojawiła się w minutę.",
        sections=[
            ("Dlaczego szybkie obiady nie wychodzą",
             """<p>Większość przepisów z hasłem „szybki obiad” zakłada, że masz w domu wszystko. W praktyce zwykle brakuje dwóch rzeczy i 20 minut zamienia się w 50, bo trzeba jeszcze wyskoczyć do sklepu. Drugi problem jest odwrotny: kiedy gotujesz na szybko, wszystko zaczyna wyglądać tak samo. Makaron, makaron, makaron. Rozwiązanie jest jedno. Niech propozycje wychodzą od tego, co faktycznie masz, a o różnorodność niech martwi się ktoś inny niż ty o siedemnastej.</p>"""),
            ("Proste obiady, które prawie zawsze da się zrobić",
             """<div class="table-wrap"><table><caption>Czasy orientacyjne, liczone od wejścia do kuchni do podania.</caption><thead><tr><th scope="col">Danie</th><th scope="col">Czas</th><th scope="col">Z czego</th></tr></thead><tbody><tr><th scope="row">Makaron z tym, co jest w lodówce</th><td>15–20 min</td><td>Makaron, ser, warzywa, ewentualnie boczek lub ciecierzyca</td></tr><tr><th scope="row">Omlet lub frittata</th><td>15 min</td><td>Jajka, resztki warzyw, ser</td></tr><tr><th scope="row">Ryż smażony z jajkiem</th><td>15 min</td><td>Wczorajszy ryż, jajka, mrożone warzywa, sos sojowy</td></tr><tr><th scope="row">Tortille i wrapy</th><td>20 min</td><td>Mięso mielone, kurczak lub fasola, tortille, surówka</td></tr><tr><th scope="row">Pierogi z zamrażarki z cebulką</th><td>20 min</td><td>Pierogi, cebula, masło, śmietana</td></tr><tr><th scope="row">Zupa krem z warzyw lub soczewicy</th><td>25–30 min</td><td>Spiżarnia plus to, co trzeba zużyć</td></tr><tr><th scope="row">Ryba z piekarnika z ziemniakami</th><td>25 min</td><td>Mrożona ryba, ziemniaki, cytryna</td></tr><tr><th scope="row">Szybki gulasz z kurczaka lub ciecierzycy</th><td>25–30 min</td><td>Pomidory z puszki, mleko kokosowe, przyprawy</td></tr></tbody></table></div><p>Wspólna cecha tych dań to tolerancja na zamiany. Nie masz kurczaka, wchodzi fasola. Nie ma papryki, wystarczy marchewka. Cibello pokazuje, które składniki masz, a których brakuje, więc od razu widzisz, czy przepis da się zrobić tak, jak jest, czy trzeba go trochę nagiąć.</p>"""),
            ("Jak dostać propozycję obiadu w niecałą minutę",
             """<ol><li>Zrób zdjęcie lodówki i spiżarni. Aplikacja rozpoznaje produkty i buduje twój domowy spis. Wynik przeglądasz i poprawiasz, bo AI może się pomylić.</li><li>Zapytaj „co na obiad?” i wybieraj spośród propozycji, które wychodzą od tego, co masz, i od tego, co trzeba zużyć najpierw.</li><li>Wybierz danie z najwyższym udziałem składników w domu. Przy każdym widzisz, dlaczego aplikacja je proponuje.</li><li>Ewentualne braki dopisz do listy zakupów.</li></ol><p>Propozycje uwzględniają też to, co niedługo się przeterminuje. Szybki obiad, który przy okazji ratuje śmietanę z krótkim terminem, jest podwójnie dobry. Więcej o tym, jak czytać daty na opakowaniach, znajdziesz w poradniku <a href="/pl/najlepiej-spozyc-przed/">najlepiej spożyć przed a należy spożyć do</a>, a o tym, jak <a href="/pl/ograniczanie-marnowania-zywnosci/">wyrzucać mniej jedzenia</a>, w osobnym tekście.</p>"""),
            ("Szybki obiad, kiedy przy stole są dzieci",
             """<p>Z dziećmi szybki obiad musi być jeszcze znajomy. Naleśniki, pierogi, kotlety mielone, makaron z sosem pomidorowym i tortille działają nie bez powodu. Sztuczka polega na tym, żeby zmieniać dodatki i białko, a nie samo danie: te same naleśniki raz z serem, raz ze szpinakiem, ta sama tortilla raz z kurczakiem, raz z fasolą. Więcej pomysłów zebraliśmy w poradniku <a href="/pl/obiady-dla-rodziny/">obiady dla rodziny z dziećmi</a>, a jeśli chcesz planować trochę dalej niż na dziś, zajrzyj do <a href="/pl/planer-posilkow/">planera posiłków</a>.</p>"""),
            ("Zamrażarka i spiżarnia to twoja rezerwa",
             """<p>Szybki obiad zaczyna się od zakupów sprzed tygodnia. Mrożona ryba, mrożone warzywa, pierogi, torebka ryżu, makaron, pomidory z puszki, fasola i ciecierzyca w słoiku, jajka i kawałek sera. Z takiego zestawu wychodzi co najmniej pięć obiadów bez wychodzenia z domu. Kiedy te produkty są w spisie Cibello, aplikacja widzi je tak samo jak świeże warzywa i podsuwa dania, które je wykorzystują, zanim zalegną na dnie zamrażarki. Listę takich dań na każdy dzień znajdziesz w <a href="/pl/pomysly-na-obiad/">pomysłach na obiad w tygodniu</a>, a jeśli chcesz, żeby ktoś wybrał za ciebie, wypróbuj losowanie na stronie <a href="/pl/co-na-obiad/">co na obiad dzisiaj</a>.</p>"""),
        ],
        faq=[
            ("Co to jest szybki obiad?", "To danie, które ugotujesz w 20 do 30 minut z produktów, które masz w domu, bez wcześniejszych zakupów."),
            ("Jak znaleźć szybki obiad z tego, co mam w domu?", "Zrób zdjęcie lodówki i spiżarni w Cibello. Aplikacja porównuje twoje produkty z przepisami i pokazuje dania, które ugotujesz teraz, z tym, co trzeba zużyć najpierw, na górze listy."),
            ("Czy zobaczę, czego brakuje w przepisie?", "Tak. Cibello pokazuje przy każdym przepisie, których składników nie masz. Składniki i alergeny zawsze sprawdzaj samodzielnie."),
            ("Jakie szybkie obiady lubią dzieci?", "Naleśniki, pierogi, makaron z sosem pomidorowym, kotlety mielone i tortille sprawdzają się najczęściej. Zmieniaj dodatki i białko zamiast całego dania."),
        ],
    ),

    "family-dinner": dict(
        slug="/pl/obiady-dla-rodziny/",
        label="Obiady dla rodziny",
        title="Obiady dla rodziny z dziećmi: pomysły | Cibello",
        desc="Pomysły na obiady dla rodziny z dziećmi: dania, które maluchy znają, jadłospis na tydzień bez kłótni przy stole i wspólna lista zakupów dla domu.",
        eyebrow="Poradnik",
        h1="Obiady dla rodziny z dziećmi: pomysły, które dzieci naprawdę zjedzą",
        lead="Dzieci lubią to, co znają. To nie znaczy, że co tydzień jecie to samo, tylko że zmiany dzieją się w obrębie dań, które już przeszły. Poniżej sposób na plan tygodnia bez kłótni przy stole i bez improwizacji o siedemnastej.",
        sections=[
            ("Dania dla dzieci, które da się zmieniać",
             """<p>Zamiast myśleć pojedynczymi przepisami, myśl rodzinami dań. Każda z nich ma kilka wersji, więc tydzień może być różnorodny, a dziecko i tak wie, co dostaje na talerz.</p><ul><li><strong>Makaron</strong>: z sosem pomidorowym, bolognese, z kurczakiem i śmietaną, z pesto, z serem i brokułem.</li><li><strong>Naleśniki</strong>: z serem na słodko, ze szpinakiem, z kurczakiem, a pod koniec tygodnia z resztkami z lodówki.</li><li><strong>Pierogi i kluski</strong>: ruskie, z mięsem, kopytka z sosem, leniwe z bułką tartą.</li><li><strong>Kotlety</strong>: mielone, z kurczaka, rybne albo z soczewicy, z ziemniakami, puree lub kaszą.</li><li><strong>Tortille i wrapy</strong>: mięso, kurczak, fasola lub ryba, a dzieci składają same.</li><li><strong>Blacha z piekarnika</strong>: kiełbasa lub kurczak z ziemniakami i warzywami, wszystko na jednej blasze.</li><li><strong>Zupa z pieczywem</strong>: pomidorowa, krem z marchewki lub rosołek, dla najmłodszych zmiksowana.</li></ul>"""),
            ("Jadłospis na tydzień dla rodziny",
             """<p><a href="/pl/planer-posilkow/">Jadłospis na tydzień</a> zmniejsza marudzenie po obu stronach: dzieci wiedzą, co będzie, a ty nie musisz wymyślać obiadu w drodze z pracy. Układ, który sprawdza się w wielu domach, to dwa szybkie ulubione dania, jedno nowe, jeden dzień na resztki i jeden „piątkowy obiad”, na który wszyscy czekają. W Cibello wpisujesz dania na poszczególne dni, a to, czego brakuje, trafia na <a href="/pl/lista-zakupow/">wspólną listę zakupów</a>, żeby osoba, która wraca przez sklep, widziała to samo co ty.</p>"""),
            ("Szybko i tanio, bez rezygnowania z wartości odżywczych",
             """<p>Rodziny z dziećmi rzadko mają czas na długie gotowanie w tygodniu, a jedzenie to duża pozycja w budżecie. Podstawa jest ta sama dla <a href="/pl/szybki-obiad/">szybkiego obiadu</a> i dla taniego gotowania: wykorzystaj to, co masz, zaplanuj resztki i dokupuj głównie to, czego brakuje. Cibello pokazuje wartości odżywcze jako orientacyjne wskazówki przy planowaniu, ale to szacunki, nie porada dietetyczna. Jeśli dziecko ma szczególne potrzeby, porozmawiaj z pediatrą lub dietetykiem.</p>"""),
            ("Alergie u dzieci",
             """<p>Jeśli któreś z dzieci ma alergię lub nietolerancję, możesz to zapisać w profilu domu, a propozycje będą filtrowane. Filtrowanie jest jednak wskazówką, nigdy gwarancją. Czytaj skład na opakowaniu i sprawdzaj produkty samodzielnie, zwłaszcza kiedy przepis się zmienia albo zamieniasz jeden składnik na inny. To samo dotyczy rozpoznawania produktów ze zdjęć: AI może się pomylić, dlatego wynik skanu przeglądasz przed zapisaniem.</p>"""),
            ("Daj dzieciom wybór",
             """<p>Dziecko, które może wybrać między dwoma obiadami albo samo złożyć swoją tortillę, częściej siada do stołu bez dyskusji. Aplikacja jest dla dorosłych (od 18 lat), ale wybór spokojnie można zrobić razem przy kuchennym stole. Cibello jest zbudowane dla całego domu: wszyscy widzą ten sam spis produktów, ten sam plan i tę samą listę zakupów, a propozycje z czasem uczą się, co u was zwykle wygrywa, więc nikt nie musi trzymać wszystkiego w głowie.</p>"""),
            ("Resztki z obiadu to jutrzejszy lunch",
             """<p>Kiedy gotujesz dla rodziny, podwójna porcja kosztuje kilka minut więcej, a daje gotowy obiad na jutro. Zupy, gulasze, bolognese i zapiekanki znoszą to bez problemu. Wystarczy przełożyć nadmiar do pudełek i dopisać je do spisu w Cibello, żeby o nich nie zapomnieć. Więcej praktycznych zasad znajdziesz w poradniku o <a href="/pl/meal-prep/">obiadach do pudełek</a>, a o tym, jak dzięki temu wyrzucać mniej, w tekście o <a href="/pl/ograniczanie-marnowania-zywnosci/">ograniczaniu marnowania żywności</a>.</p>"""),
        ],
        faq=[
            ("Jakie obiady lubią dzieci?", "Makaron, naleśniki, pierogi, kotlety mielone, tortille i dania z jednej blachy sprawdzają się u większości dzieci. Zmieniaj sosy, dodatki i białko zamiast całego dania."),
            ("Jak ułożyć jadłospis na tydzień dla rodziny?", "Wybierz dwa szybkie ulubione dania, jedno nowe, jeden dzień na resztki i jeden obiad na koniec tygodnia. W Cibello wpisujesz dania na poszczególne dni, a brakujące produkty trafiają na wspólną listę zakupów."),
            ("Czy Cibello uwzględni alergie dzieci?", "Alergie możesz zapisać w profilu domu, ale filtrowanie jest wskazówką. Zawsze sprawdzaj skład i opakowanie samodzielnie."),
            ("Czy wartości odżywcze w aplikacji są dostosowane do dzieci?", "Wartości odżywcze to orientacyjne szacunki do planowania, nie porada dietetyczna. Przy szczególnych potrzebach skonsultuj się z pediatrą lub dietetykiem."),
        ],
    ),

    "meal-boxes": dict(
        slug="/pl/meal-prep/",
        label="Meal prep",
        title="Meal prep: obiady do pudełek na cały tydzień | Cibello",
        desc="Meal prep po polsku: które dania dobrze znoszą pudełko, jak zaplanować tydzień, ile obiad wytrzyma w lodówce i jak nie zapomnieć o pojemniku z tyłu półki.",
        eyebrow="Poradnik",
        h1="Meal prep po polsku: obiady do pudełek na cały tydzień",
        lead="Dobry obiad do pudełka wytrzymuje dzień lub dwa w lodówce i kilka minut w mikrofalówce, a dalej smakuje. Podpowiadamy, które dania to lubią, jak zaplanować tydzień i jak nie zapomnieć o pudełku z tyłu lodówki.",
        sections=[
            ("Dania, które dobrze znoszą pudełko",
             """<p>Gulasze, curry, chili, leczo, bigos, gołąbki, zapiekanki makaronowe i ziemniaczane, sałatki na kaszy lub ryżu, pieczone warzywa z białkiem: to pewniaki. Zupy też, byle w szczelnym pojemniku. Gorzej znoszą to rzeczy z chrupiącym dodatkiem, świeżą sałatą lub jajkiem sadzonym, które lepiej dołożyć na miejscu. Najprostsza zasada: gotujesz podwójną porcję zwykłego obiadu i masz pudełka bez dodatkowej pracy. Dania, które się do tego nadają, znajdziesz wśród <a href="/pl/domowe-obiady/">domowych obiadów na co dzień</a>.</p>"""),
            ("Jak zaplanować pudełka na tydzień",
             """<ol><li>Wybierz dwa dania, które dobrze znoszą przechowywanie, i ugotuj podwójne porcje w niedzielę lub poniedziałek.</li><li>Zmieniaj dodatki: ten sam gulasz raz z kaszą, raz z ryżem i jogurtem, raz z pieczywem.</li><li>Połowę zamroź od razu. Pudełka z lodówki zjedz w ciągu dwóch, trzech dni; mrożone wytrzymają znacznie dłużej.</li><li>Dopisz pudełka do spisu produktów w Cibello, żeby było widać, co jest i co zjeść najpierw.</li></ol><p>Resztki zapisane jako pudełka są w spisie razem z innymi produktami, więc przy planowaniu kolejnego dnia w <a href="/pl/planer-posilkow/">planerze posiłków</a> masz je przed oczami. Resztki stają się częścią planu, a nie niespodzianką.</p>"""),
            ("Pilnuj lodówki i zamrażarki",
             """<p>Najwięcej jedzenia marnuje się przez zapominanie. Pudełko schowane w głębi lodówki to klasyk. W Cibello pudełka mogą być częścią twojego spisu produktów, a aplikacja delikatnie przypomina, kiedy coś warto zjeść. Nie ma wstydu ani liczników wyrzuconego jedzenia, jest tylko przypomnienie w porę. Nie wiesz, ile coś wytrzyma? Zajrzyj do poradnika o <a href="/pl/najlepiej-spozyc-przed/">datach na opakowaniach</a> i zawsze kieruj się zapachem, wyglądem i zdrowym rozsądkiem.</p>"""),
            ("Bezpieczeństwo i przechowywanie",
             """<ul><li>Schłodź jedzenie szybko po ugotowaniu i wstaw do lodówki najpóźniej w ciągu dwóch godzin.</li><li>Podgrzewaj pudełko porządnie, tak żeby parowało w całości, nie tylko na brzegach.</li><li>Ryż i makaron schładzaj szybko i zjadaj w ciągu kilku dni.</li><li>Oznaczaj mrożone pudełka zawartością i datą albo pozwól, żeby pilnowała tego aplikacja.</li><li>Rozmrażaj w lodówce, nie na blacie, zwłaszcza dania z mięsem i rybą.</li></ul><p>Daty i rozpoznane przez AI produkty w aplikacji to wsparcie, nie wyrocznia. Zawsze sprawdź samodzielnie, zanim zjesz, szczególnie jeśli gotujesz dla dzieci, osób w ciąży lub z obniżoną odpornością.</p>"""),
            ("Pudełko do pracy, które nie nudzi",
             """<p>Sekret nie tkwi w liczbie przepisów, tylko w dodatkach i sosach. Jedna baza, na przykład pieczony kurczak z warzywami, w poniedziałek idzie z kaszą i jogurtem, w środę jako wrap z sałatą, w piątek do sałatki z fetą. Trzymaj w pracy małą buteleczkę oliwy, sos sojowy i cytrynę, a te same składniki będą smakować inaczej. Kiedy planujesz w Cibello, widzisz, ile z potrzebnych produktów masz w domu, a brakujące trafiają na <a href="/pl/lista-zakupow/">wspólną listę zakupów</a>.</p>"""),
        ],
        faq=[
            ("Jakie dania nadają się do pudełek?", "Gulasze, curry, chili, bigos, zapiekanki, sałatki na kaszy lub ryżu i pieczone warzywa z białkiem dobrze znoszą zarówno lodówkę, jak i mikrofalówkę."),
            ("Ile obiad w pudełku wytrzyma w lodówce?", "Licz się z dwoma, trzema dniami w lodówce i znacznie dłużej w zamrażarce. Schładzaj szybko, podgrzewaj porządnie i zawsze sprawdzaj zapach i wygląd."),
            ("Czy Cibello pomoże mi pilnować pudełek?", "Tak. Pudełka można dopisać do spisu produktów, a aplikacja przypomina, kiedy coś warto zjeść."),
            ("Czy resztki mogą być częścią planu?", "Tak. Resztki zapisane jako pudełka są w spisie produktów i można je uwzględnić, planując obiad na kolejny dzień."),
        ],
    ),

    "shopping-list": dict(
        slug="/pl/lista-zakupow/",
        label="Lista zakupów",
        title="Lista zakupów dla całej rodziny w aplikacji | Cibello",
        desc="Lista zakupów, która powstaje z tego, czego naprawdę brakuje do zaplanowanych dań, i jest wspólna dla całego domu. Mniej podwójnych zakupów, mniej wyrzucania.",
        eyebrow="Poradnik",
        h1="Lista zakupów, którą widzi cały dom i która wie, co masz w lodówce",
        lead="Zwykła lista zakupów pisana z pamięci jest albo za długa, albo za krótka. W Cibello lista powstaje z tego, czego naprawdę brakuje do zaplanowanych dań, i jest wspólna dla wszystkich domowników.",
        sections=[
            ("Problem ze zwykłą listą zakupów",
             """<p>Większość list pisze jedna osoba, z głowy, w pośpiechu. Efekt: albo lista jest za długa i kupujesz drugi słoik musztardy, bo pierwszy stoi za mlekiem, albo za krótka i do obiadu brakuje jednej rzeczy. Aplikacje do list rozwiązują dzielenie się listą, ale nie łączą jej z tym, co faktycznie jest w domu, ani z tym, co ma być ugotowane. W efekcie nadal ktoś musi trzymać wszystko w pamięci.</p>"""),
            ("Jak działa lista zakupów w Cibello",
             """<ol><li><strong>Wychodzi od spisu produktów.</strong> Kiedy planujesz danie, jego składniki są porównywane z tym, co już masz w lodówce, zamrażarce i spiżarni. Na listę trafia tylko to, czego brakuje.</li><li><strong>Uzupełnia się z planu tygodnia.</strong> Kiedy planujesz obiady na kilka dni, wszystkie braki zbierają się w jednej liście.</li><li><strong>Jest wspólna dla domu.</strong> Wszyscy domownicy widzą tę samą listę i mogą odhaczać produkty w sklepie.</li><li><strong>Aktualizuje spis po zakupach.</strong> Zrób zdjęcie paragonu albo zeskanuj kody kreskowe, a produkty wrócą do spisu. Wynik przeglądasz, bo AI może się pomylić.</li></ol><p>Oczywiście możesz też dopisywać rzeczy ręcznie: proszek do prania, kawę albo to, co „zawsze ma być w domu”.</p>"""),
            ("Wspólna lista dla całego domu",
             """<p>Funkcja domu w Cibello służy temu, żeby kilka osób pracowało na tym samym spisie produktów, tym samym <a href="/pl/planer-posilkow/">planie posiłków</a> i tej samej liście zakupów. Osoba wracająca z pracy widzi, czego brakuje, a osoba planująca nie musi wysyłać listy osobno na komunikatorze. W okresie próbnym albo z planem płatnym cały dom ma wspólny podgląd. Konto zakłada osoba dorosła, bo aplikacja jest dla osób od 18 lat.</p>"""),
            ("Lista, która zmniejsza marnowanie i wydatki",
             """<p>Kiedy na liście jest tylko to, czego brakuje, znika większość podwójnych zakupów. Kiedy dania z produktów o krótkim terminie planujesz najpierw, mniej ląduje w koszu. To ta sama zasada, którą opisujemy w poradniku o <a href="/pl/ograniczanie-marnowania-zywnosci/">ograniczaniu marnowania żywności</a>: najpierw przegląd tego, co masz, dopiero potem zakupy. Nie potrzebujesz do tego arkusza ani liczenia; wystarczy, że spis w aplikacji jest w miarę aktualny.</p>"""),
            ("Kilka nawyków, które robią różnicę",
             """<ul><li>Planuj zakupy raz, dwa razy w tygodniu, nie codziennie. Każde wejście do sklepu to dodatkowe rzeczy w koszyku.</li><li>Zanim dopiszesz coś do listy, sprawdź spis. Często okazuje się, że produkt jest, tylko stoi za czymś innym.</li><li>Zdjęcie paragonu od razu po zakupach zajmuje chwilę, a utrzymuje spis w porządku.</li><li>Zostaw miejsce na jeden dzień z resztek: wtedy lista jest krótsza, a lodówka pustsza, w dobrym sensie.</li></ul><p>Jeśli chcesz zobaczyć, jak to wygląda z drugiej strony, czyli od przepisu do zakupów, zajrzyj do poradnika <a href="/pl/przepisy-z-produktow/">przepisy z produktów, które masz</a>. A jeśli gotujesz na zapas, przyda się tekst o <a href="/pl/meal-prep/">obiadach do pudełek</a>.</p>"""),
        ],
        faq=[
            ("Czy cały dom widzi tę samą listę zakupów?", "Tak. Funkcja domu w Cibello udostępnia spis produktów, plan posiłków i listę zakupów wszystkim członkom domu."),
            ("Czy lista zakupów uzupełnia się sama?", "Tak. Kiedy planujesz przepis albo tydzień obiadów, składniki, których nie ma w spisie produktów, trafiają na listę."),
            ("Czy mogę dopisać własne produkty?", "Tak, wszystko da się dopisać ręcznie, także rzeczy, które nie są jedzeniem."),
            ("Czy spis produktów aktualizuje się po zakupach?", "Możesz zrobić zdjęcie paragonu albo zeskanować kody kreskowe, a produkty trafią do spisu. Sprawdź wynik, bo AI może odczytać coś błędnie."),
        ],
    ),

    "best-before": dict(
        slug="/pl/najlepiej-spozyc-przed/",
        label="Daty na opakowaniach",
        title="Najlepiej spożyć przed a należy spożyć do | Cibello",
        desc="Czym różni się „najlepiej spożyć przed” od „należy spożyć do”, co można jeść po dacie, ile wytrzymują popularne produkty i jak pilnować terminów bez kartki.",
        eyebrow="Poradnik",
        h1="Najlepiej spożyć przed a należy spożyć do: co naprawdę znaczą daty na opakowaniach",
        lead="Dwa napisy, dwa zupełnie różne znaczenia. Jeden mówi o jakości, drugi o bezpieczeństwie. Kto je rozróżnia, wyrzuca mniej jedzenia i nie ryzykuje tam, gdzie nie warto.",
        sections=[
            ("„Najlepiej spożyć przed”: granica jakości",
             """<p><strong>Najlepiej spożyć przed</strong> (data minimalnej trwałości) mówi, do kiedy producent gwarantuje pełną jakość: smak, konsystencję i wartość odżywczą. Po tej dacie produkt często nadal nadaje się do jedzenia, pod warunkiem że był dobrze przechowywany, a opakowanie jest nienaruszone. Dotyczy to na przykład mleka UHT, jogurtów, jajek, serów twardych, konserw, produktów sypkich i mrożonek. Zasady oznaczania dat są wspólne dla całej Unii Europejskiej, a w Polsce nad bezpieczeństwem żywności czuwa Państwowa Inspekcja Sanitarna. Praktyczna rada jest prosta: popatrz, powąchaj, spróbuj. To dobry sposób, żeby ocenić, czy produkt po dacie minimalnej trwałości nadaje się jeszcze do jedzenia.</p>"""),
            ("„Należy spożyć do”: granica bezpieczeństwa",
             """<p><strong>Należy spożyć do</strong> (termin przydatności do spożycia) pojawia się na produktach wrażliwych, w których bakterie mogą się namnażać, mimo że jedzenie nie śmierdzi ani nie wygląda źle. To między innymi surowy kurczak, mięso mielone, świeża ryba, część wędlin i gotowych dań. Po tej dacie produktu nie należy jeść. Najbezpieczniej ugotować go lub zamrozić najpóźniej w dniu wskazanym na opakowaniu. Mrożenie zatrzymuje zegar, a zamrożony produkt można przygotować po rozmrożeniu.</p>"""),
            ("Ile wytrzymują popularne produkty?",
             """<div class="table-wrap"><table><caption>Wartości orientacyjne dla produktów nieotwartych i dobrze przechowywanych.</caption><thead><tr><th scope="col">Produkt</th><th scope="col">Orientacyjnie po dacie minimalnej trwałości</th><th scope="col">Uwagi</th></tr></thead><tbody><tr><th scope="row">Mleko i kefir</th><td>Kilka dni do tygodnia</td><td>Powąchaj i spróbuj; skwaśniałe mleko czuć od razu</td></tr><tr><th scope="row">Jogurt i twaróg</th><td>Często tydzień lub dłużej</td><td>Kwas chroni; sprawdź, czy nie ma pleśni</td></tr><tr><th scope="row">Jajka</th><td>Kilka tygodni</td><td>Jeśli jajko pływa w wodzie, wyrzuć je</td></tr><tr><th scope="row">Ser twardy</th><td>Tygodnie, nawet miesiące</td><td>Pleśń z powierzchni sera twardego można odkroić</td></tr><tr><th scope="row">Konserwy i produkty sypkie</th><td>Miesiące, nawet lata</td><td>Wyrzuć puszki wybrzuszone lub wgniecione</td></tr><tr><th scope="row">Mrożonki</th><td>Miesiące</td><td>Jakość spada, bezpieczeństwo zostaje</td></tr><tr><th scope="row">Ugotowane mięso mielone, kurczak</th><td>2–3 dni w lodówce</td><td>Schłodź szybko, podgrzej porządnie</td></tr><tr><th scope="row">Ugotowany ryż i makaron</th><td>Kilka dni w lodówce</td><td>Schłodź od razu po ugotowaniu</td></tr></tbody></table></div><p>Tabela to orientacja, nie reguła. Zawsze czytaj zalecenia na opakowaniu i ufaj własnym zmysłom, a z jedzeniem dla dzieci, osób w ciąży i osób z obniżoną odpornością bądź ostrożniejszy niż zwykle.</p>"""),
            ("Jak przechowywać, żeby daty miały sens",
             """<p>Nawet najlepszy termin nie pomoże, jeśli mleko stoi w drzwiach lodówki, a mięso na górnej półce obok sałaty. Najzimniejsze miejsce w lodówce to zwykle dolna półka nad szufladami: tam trzymaj mięso i ryby. Nabiał na środkowych półkach, otwarte słoiki i gotowe dania wyżej, warzywa w szufladach. Produkty z krótszą datą przesuwaj do przodu, kiedy wkładasz nowe zakupy. Otwarte opakowanie skraca termin bez względu na to, co jest napisane z przodu, więc zerknij na dopisek „po otwarciu spożyć w ciągu”.</p>"""),
            ("Jak pilnować dat bez kartki na lodówce",
             """<p>Trudne nie są zasady, tylko pamiętanie o nich. W Cibello produkty są w twoim spisie razem z datami, z paragonów, kodów kreskowych albo ze zdjęć, a aplikacja delikatnie sygnalizuje, kiedy coś warto zużyć w najbliższych dniach. <a href="/pl/przepisy-z-produktow/">Propozycje dań</a> stawiają wtedy wyżej przepisy z tymi właśnie produktami. Tak <a href="/pl/ograniczanie-marnowania-zywnosci/">mniejsze marnowanie żywności</a> staje się skutkiem ubocznym gotowania obiadu, a resztki spokojnie lądują w <a href="/pl/meal-prep/">pudełkach na jutro</a>. AI może odczytać datę błędnie, dlatego zawsze sprawdzaj ją samodzielnie.</p>"""),
        ],
        faq=[
            ("Czym różni się „najlepiej spożyć przed” od „należy spożyć do”?", "Najlepiej spożyć przed to granica jakości: produkt często nadaje się do jedzenia po tej dacie, jeśli był dobrze przechowywany. Należy spożyć do to granica bezpieczeństwa dla produktów wrażliwych, takich jak kurczak i mięso mielone, i nie należy jej przekraczać."),
            ("Czy można jeść produkty po dacie minimalnej trwałości?", "Często tak. Popatrz, powąchaj, spróbuj. Nie dotyczy to produktów oznaczonych „należy spożyć do”."),
            ("Ile mleko wytrzyma po dacie na opakowaniu?", "Zwykle kilka dni do tygodnia, jeśli było nieotwarte i trzymane w lodówce. Decydują zapach i smak."),
            ("Czy aplikacja przypomni mi, zanim jedzenie się zepsuje?", "Tak. Cibello trzyma daty w spisie produktów, przypomina, kiedy coś warto zużyć, i proponuje przepisy z tym produktem. Daty zawsze sprawdzaj samodzielnie."),
        ],
    ),

    "weekday-dinners": dict(
        slug="/pl/pomysly-na-obiad/",
        label="Pomysły na obiad",
        title="Pomysły na obiad w tygodniu: 25 dań | Cibello",
        desc="25 pomysłów na obiad w tygodniu posortowanych według czasu: co ugotujesz w kwadrans, w 25 minut i w pół godziny, z produktów, które zwykle są w domu.",
        eyebrow="Poradnik",
        h1="Pomysły na obiad w tygodniu: 25 dań posortowanych według czasu",
        lead="Zamiast jednej długiej listy przepisów do przewijania, trzy krótkie: co ugotujesz w kwadrans, co w 25 minut, a co w pół godziny. Do tego sposób, żeby wybór zaczynał się od lodówki, a nie od książki kucharskiej.",
        sections=[
            ("Gotowe w 15 minut",
             """<ul><li><strong>Makaron z tuńczykiem</strong>: makaron, tuńczyk z puszki, śmietana, cytryna.</li><li><strong>Ryż smażony z jajkiem</strong>: wczorajszy ryż, jajka, mrożone warzywa, sos sojowy.</li><li><strong>Pizza na tortilli</strong>: tortilla, sos pomidorowy, ser i to, co jest w lodówce.</li><li><strong>Makaron z pesto i kurczakiem</strong>: resztki kurczaka z wczoraj albo z rożna.</li><li><strong>Omlet z serem i warzywami</strong>: ratuje jajka i połówki warzyw.</li><li><strong>Zapiekanki z bułki</strong>: bułka, ser, pieczarki, cebula, ketchup.</li><li><strong>Kanapki z pastą jajeczną i pomidorem</strong>: kolacja, która spokojnie robi za obiad.</li></ul>"""),
            ("Gotowe w 20 do 25 minut",
             """<ul><li><strong>Kiełbasa z patelni z cebulą i ziemniakami</strong>.</li><li><strong>Kurczak z warzywami z patelni i makaronem</strong>.</li><li><strong>Tortille</strong> z mięsem mielonym, kurczakiem lub fasolą.</li><li><strong>Spaghetti carbonara</strong>.</li><li><strong>Ryba z piekarnika z ziemniakami i cytryną</strong>.</li><li><strong>Pierogi z zamrażarki z cebulką i śmietaną</strong>.</li><li><strong>Zupa pomidorowa z ryżem</strong>.</li><li><strong>Ciecierzyca w sosie pomidorowym ze szpinakiem</strong>.</li><li><strong>Placki z cukinii z sosem jogurtowym</strong>.</li><li><strong>Sałatka z kaszą, fetą i pieczonymi warzywami</strong>.</li></ul>"""),
            ("Gotowe w 30 minut",
             """<ul><li><strong>Kurczak w sosie pieczarkowym ze śmietaną</strong>.</li><li><strong>Zupa z soczewicy z pieczywem</strong>.</li><li><strong>Chili sin carne</strong>.</li><li><strong>Kurczak curry z mlekiem kokosowym</strong>: ugotuj podwójnie, do pudełek.</li><li><strong>Kotlety mielone z puree i surówką</strong>.</li><li><strong>Blacha z kiełbasą i warzywami korzeniowymi</strong>.</li><li><strong>Zapiekanka makaronowa z brokułem i serem</strong>.</li><li><strong>Kotlety z fasoli z ziemniakami</strong>.</li></ul><p>Więcej szybkich dań, z tabelą czasu i składników, znajdziesz w poradniku <a href="/pl/szybki-obiad/">szybki obiad w 20 do 30 minut</a>. Jeśli przy stole siedzą dzieci, zajrzyj do <a href="/pl/obiady-dla-rodziny/">obiadów dla rodziny z dziećmi</a>.</p>"""),
            ("Trik: niech lodówka wybiera",
             """<p>Każde z dań wyżej wymaga, żeby składniki naprawdę były w domu. To właśnie tu wieczorny obiad zwykle się sypie: wybierasz danie, a potem odkrywasz, że papryka się skończyła. Cibello odwraca kolejność. Zrób zdjęcie lodówki i spiżarni, aplikacja wie, co jest, a <a href="/pl/przepisy-z-produktow/">propozycje dań</a> są ustawione według tego, jaki procent składników masz, z produktami o krótkim terminie na górze. Cztery dni robocze naraz zamieniają się w <a href="/pl/planer-posilkow/">plan posiłków</a>, a braki lądują na <a href="/pl/lista-zakupow/">wspólnej liście zakupów</a>. Wynik rozpoznawania zawsze przeglądasz, bo AI może się pomylić.</p>"""),
            ("Rotacja wygrywa z inspiracją",
             """<p>Większość domów gotuje 10 do 15 dań na zmianę i to nie jest problem. Sposób na różnorodność to zamiana białka i dodatków, a nie całego dania: ten sam gulasz raz z kurczakiem, raz z ciecierzycą, te same tortille z rybą zamiast mięsa mielonego. Cibello uczy się, co u was zwykle wygrywa, i proponuje warianty podobne do ulubionych, ale z tego, co akurat jest w domu. <a href="/pl/domowe-obiady/">Więcej o domowych obiadach, które wytrzymują cały tydzień</a>.</p>"""),
            ("Kiedy naprawdę nie masz pomysłu",
             """<p>Bywa, że lista nie pomaga, bo każdy pomysł wydaje się taki sam. Wtedy sprawdza się najprostsze narzędzie: losowanie. Na stronie <a href="/pl/co-na-obiad/">co na obiad dzisiaj</a> wybierasz białko, czas i tryb, a w sekundę dostajesz jedną propozycję zamiast czterdziestu. Jedna propozycja to decyzja, czterdzieści to kolejne przewijanie.</p>"""),
        ],
        faq=[
            ("Jakie są dobre pomysły na obiad w tygodniu?", "Dania na 15 do 30 minut z produktów, które zwykle są w domu: makaron, jajka, patelnia z ryżem, tortille, zupy, gulasze i dania z jednej blachy. Lista wyżej zawiera 25 takich dań."),
            ("Jak znaleźć pomysł na obiad z tego, co mam w domu?", "Zrób zdjęcie lodówki i spiżarni w Cibello. Aplikacja ustawia ponad 9 000 przepisów według tego, jaki procent składników już masz."),
            ("Jak mieć różnorodne obiady bez wymyślania nowych przepisów?", "Zmieniaj białko i dodatki zamiast całego dania, planuj trzy do czterech obiadów naraz i zostaw jeden dzień na resztki."),
            ("Czy Cibello zaplanuje obiady na kilka dni?", "Tak. Możesz ułożyć plan na kilka dni, a brakujące składniki trafią na wspólną listę zakupów. Plan przeglądasz i zmieniasz samodzielnie."),
        ],
    ),

    "what-to-eat-tonight": dict(
        slug="/pl/co-na-obiad/",
        label="Co na obiad?",
        title="Co na obiad dzisiaj? Wylosuj pomysł | Cibello",
        desc="Co na obiad dzisiaj? Wybierz białko, czas i tryb, a narzędzie wylosuje jedno z 40 codziennych dań. Do tego trzy pytania, które prawie zawsze dają odpowiedź.",
        eyebrow="Narzędzie i poradnik",
        h1="Co na obiad dzisiaj?",
        lead="Codzienne pytanie, które potrafi zająć więcej czasu niż samo gotowanie. Poniżej narzędzie, które losuje jedną propozycję w kilka sekund, i trzy pytania, które prawie zawsze prowadzą do odpowiedzi.",
        sections=[
            ("Dlaczego to pytanie jest takie trudne",
             """<p>Wybór obiadu to żonglowanie czterema rzeczami naraz: co masz w domu, ile jest czasu, co zjedzą wszyscy przy stole i co trzeba zużyć, zanim się zepsuje. Robienie tego w głowie każdego wieczoru to realne obciążenie. Większość ludzi kończy na tych samych trzech daniach albo na jedzeniu na wynos nie dlatego, że brakuje im pomysłów, tylko dlatego, że samo decydowanie męczy.</p>"""),
            ("Trzy pytania, które dają odpowiedź",
             """<ol><li><strong>Co w domu trzeba zużyć?</strong> Zacznij od lodówki, nie od przepisu. Produkt z krótkim terminem podpowiada danie.</li><li><strong>Ile masz czasu i siły?</strong> Poniżej 20 minut: makaron, omlet, patelnia z ryżem, tortille. Więcej czasu: gulasz, blacha z piekarnika, zupa.</li><li><strong>Kto będzie jadł?</strong> Dzieci, goście czy tylko ty decydują o tym, jak znajome albo jak ambitne może być danie.</li></ol><p>Cibello zadaje te trzy pytania za ciebie. Aplikacja wie, co masz, dzięki zdjęciu lodówki albo zeskanowanemu paragonowi, a propozycje przychodzą z wyjaśnieniem: „bo masz kurczaka i śmietanę, którym kończy się termin, a u was lubicie kremowe sosy”. Zobacz też <a href="/pl/szybki-obiad/">szybki obiad w 20 do 30 minut</a> i <a href="/pl/przepisy-z-produktow/">przepisy z produktów, które masz</a>.</p>"""),
            ("Co ugotować, kiedy „nic nie ma w domu”",
             """<p>Prawie zawsze masz więcej, niż ci się wydaje. Makaron, ryż lub kasza, jajka, puszka pomidorów, słoik fasoli, cebula, mrożone warzywa i kawałek sera wystarczą na co najmniej pięć obiadów: makaron z pomidorami i fasolą, omlet, ryż smażony, zupa z soczewicy, pizza na tortilli. Spis produktów w Cibello pokazuje dokładnie, co jest, także to, co schowało się z tyłu półki. Kiedy spis jest aktualny, propozycje dań zaczynają się od tych produktów, a nie od zakupów. Więcej dań dzień po dniu znajdziesz w <a href="/pl/pomysly-na-obiad/">pomysłach na obiad w tygodniu</a>.</p>"""),
            ("Co podać, kiedy przychodzą goście",
             """<p>Z gośćmi obowiązują inne zasady: wybierz coś, co da się przygotować wcześniej (gulasz, zapiekanka, pieczony kurczak), co zniesie czekanie i co już kiedyś było u ciebie na stole. Czas przeznacz na dodatki i nakrycie stołu. Jeśli planujesz w tygodniu, braki trafią na <a href="/pl/lista-zakupow/">listę zakupów</a>, a resztki zamienią się w <a href="/pl/meal-prep/">poniedziałkowe pudełko do pracy</a>.</p>"""),
            ("Jak pozbyć się tego pytania na dobre",
             """<p>Kto planuje trzy do pięciu obiadów naraz, nie stoi przed lodówką o siedemnastej. <a href="/pl/planer-posilkow/">Plan posiłków</a> z daniami, które zużywają produkty we właściwej kolejności, wspólna lista zakupów i łagodne przypomnienia, zanim coś się zepsuje, zdejmują jednocześnie decyzję i marnowanie. To właśnie robi Cibello. Zaczynasz od zdjęcia lodówki, aplikacja rozpoznaje produkty, ty sprawdzasz wynik, a resztą zajmują się propozycje. Przez 14 dni możesz wypróbować wszystko bez podawania karty; aplikacja jest dla osób od 18 lat. Jeśli chcesz wiedzieć, jak radzić sobie z tym, co zostaje, zajrzyj do tekstu o <a href="/pl/ograniczanie-marnowania-zywnosci/">ograniczaniu marnowania żywności</a>.</p>"""),
        ],
        faq=[
            ("Co na obiad, kiedy nie mam żadnego pomysłu?", "Skorzystaj z narzędzia wyżej albo wyjdź od tego, co masz w domu: makaron, omlet, patelnia z ryżem, tortille, zupa lub blacha z piekarnika załatwiają większość wieczorów. Cibello proponuje dania na podstawie twojego spisu produktów."),
            ("Co na obiad wegetariańskiego?", "Zupa z soczewicy, chili sin carne, ciecierzyca w pomidorach, kotlety z fasoli, pierogi ruskie, zapiekanka z brokułem i serem albo szakszuka. Wszystko w mniej niż 30 minut z produktów ze spiżarni."),
            ("Co ugotować z tego, co mam w lodówce?", "Zrób zdjęcie lodówki i spiżarni w Cibello. Aplikacja ustawia ponad 9 000 przepisów według tego, jaki procent składników już masz."),
            ("Jak przestać codziennie myśleć o obiedzie?", "Planuj trzy do pięciu obiadów naraz, korzystaj z listy zakupów, która uzupełnia się z planu, i zużywaj produkty z krótkim terminem najpierw."),
        ],
    ),
}

TOOL = dict(
    heading="Losowanie obiadu: podpowiedź w 10 sekund",
    protein_label="Białko", time_label="Czas", mode_label="Tryb",
    protein={"any": "Dowolne", "chicken": "Kurczak", "meat": "Mięso", "fish": "Ryba", "veg": "Wegetariańskie"},
    time={"20": "Do 20 min", "30": "Do 30 min", "45": "Do 45 min", "90": "Bez znaczenia"},
    mode={"all": "Wszystkie", "quick": "Szybko", "leftovers": "Wykorzystaj resztki", "pantry": "Tylko ze spiżarni", "budget": "Tanio", "kids": "Dla dzieci", "mealbox": "Zostanie na jutro", "friday": "Piątkowy wieczór"},
    button="Wylosuj obiad",
    no_match="Nic nie pasuje. Spróbuj poluzować jeden z filtrów.",
    minutes="min",
    any_protein="dowolne białko",
    tip="W aplikacji Cibello propozycje zaczynają się od tego, co naprawdę masz w lodówce.",
    note="Narzędzie losuje spośród czterdziestu codziennych dań i nie wymaga konta. W aplikacji propozycje wychodzą od tego, co faktycznie masz w lodówce.",
    dishes=[
        ("Pizza na tortilli z tym, co jest w lodówce", "any", 15, ["quick", "kids", "friday"]),
        ("Ryż smażony z jajkiem i resztkami", "any", 15, ["leftovers", "pantry", "budget"]),
        ("Sałatka z kaszą i resztkami z obiadu", "any", 20, ["mealbox", "leftovers", "quick"]),
        ("Zapiekanki z bułki z serem i dodatkami", "any", 15, ["budget", "kids", "quick"]),
        ("Wrapy z tortilli z tym, co masz", "any", 20, ["leftovers", "quick", "kids"]),
        ("Kotlety z kurczaka w panierce z ziemniakami i surówką", "chicken", 30, ["kids"]),
        ("Kurczak w sosie curry z ryżem", "chicken", 30, ["mealbox", "leftovers"]),
        ("Pierś z kurczaka w sosie pieczarkowym z makaronem", "chicken", 30, ["kids"]),
        ("Zupa z kurczaka z makaronem i warzywami", "chicken", 45, ["kids", "mealbox", "budget"]),
        ("Kurczak pieczony z warzywami na jednej blasze", "chicken", 45, ["kids", "mealbox"]),
        ("Makaron z kurczakiem i szpinakiem", "chicken", 20, ["quick"]),
        ("Gyros z kurczaka w picie z sosem czosnkowym", "chicken", 25, ["friday", "kids"]),
        ("Kurczak z warzywami z patelni i ryżem", "chicken", 20, ["quick", "leftovers"]),
        ("Kotlety mielone z ziemniakami i buraczkami", "meat", 35, ["kids", "budget"]),
        ("Schabowy z ziemniakami i kapustą zasmażaną", "meat", 40, ["kids", "friday"]),
        ("Gulasz wieprzowy z kaszą gryczaną", "meat", 60, ["mealbox", "leftovers"]),
        ("Gołąbki bez zawijania z ryżem i mięsem", "meat", 45, ["mealbox", "budget"]),
        ("Spaghetti bolognese", "meat", 30, ["kids", "mealbox"]),
        ("Kiełbasa z patelni z cebulą i ziemniakami", "meat", 20, ["quick", "budget"]),
        ("Leczo z kiełbasą i papryką", "meat", 30, ["budget", "mealbox", "leftovers"]),
        ("Szybki bigos z kiszonej kapusty i kiełbasy", "meat", 45, ["pantry", "mealbox"]),
        ("Zapiekanka ziemniaczana z mięsem mielonym", "meat", 45, ["kids", "leftovers", "mealbox"]),
        ("Fasolka po bretońsku", "meat", 30, ["pantry", "budget", "mealbox"]),
        ("Domowe burgery z frytkami z piekarnika", "meat", 30, ["friday", "kids"]),
        ("Ryba pieczona z ziemniakami i cytryną", "fish", 25, ["quick", "kids"]),
        ("Makaron z tuńczykiem, kukurydzą i śmietaną", "fish", 15, ["pantry", "quick", "budget"]),
        ("Łosoś z piekarnika z kaszą i brokułem", "fish", 30, ["mealbox", "friday"]),
        ("Ryba po grecku", "fish", 40, ["leftovers", "friday"]),
        ("Dorsz smażony z frytkami i surówką", "fish", 30, ["friday", "kids"]),
        ("Sałatka z tuńczykiem, jajkiem i fasolą", "fish", 15, ["pantry", "quick", "mealbox"]),
        ("Pierogi ruskie z cebulką", "veg", 20, ["kids", "budget", "quick"]),
        ("Naleśniki z serem", "veg", 30, ["kids", "budget"]),
        ("Placki ziemniaczane ze śmietaną", "veg", 35, ["budget", "kids"]),
        ("Zupa pomidorowa z ryżem lub makaronem", "veg", 30, ["kids", "budget", "pantry"]),
        ("Krupnik z warzywami", "veg", 45, ["mealbox", "budget"]),
        ("Kopytka z sosem grzybowym", "veg", 40, ["kids"]),
        ("Makaron z pesto, cukinią i fetą", "veg", 20, ["quick", "mealbox"]),
        ("Kotlety z soczewicy z surówką", "veg", 35, ["budget", "mealbox"]),
        ("Zupa ogórkowa z ziemniakami", "veg", 40, ["pantry", "leftovers", "mealbox"]),
        ("Szakszuka z pieczywem", "veg", 20, ["pantry", "quick"]),
    ],
)
